"use client";
import { useId, useState } from "react";
import BusinessActionForm from "@/components/BusinessActionForm";
import { countryCallingCodes } from "@/lib/countryCallingCodes";
import { businessDocumentLabels, purchasingPurposes, identityDocumentTypes, representativeRoles } from "@/lib/business-verification";
import { submitBusinessApplication } from "./actions";
import s from "./BusinessVerificationForm.module.css";
const explanations:Record<keyof typeof businessDocumentLabels,string>={registration:"Registration, incorporation or tax certificate showing your legal business name.",address:"Utility bill, lease or official document showing the registered business address.",ownership:"List the owners, ownership percentages and controlling persons. A sole proprietor can declare 100% ownership.",identity:"A clear, valid photo ID for the representative named above. Include both sides if applicable in one file.",personal_address:"A recent utility bill, bank statement or official document showing the representative's name and residential address."};
function Upload({kind}:{kind:keyof typeof businessDocumentLabels}) {return <label className={`${s.field} ${s.upload}`}><span>{businessDocumentLabels[kind]} *</span><small>{explanations[kind]}</small><input name={kind} type="file" required accept="application/pdf,image/jpeg,image/png" onChange={e=>{const file=e.target.files?.[0];e.target.setCustomValidity(file&&file.size>1024*1024?"Choose a file no larger than 1 MB.":"");}}/><small>PDF, JPG or PNG · Maximum 1 MB</small></label>;}
function Heading({number,title,description}:{number:string;title:string;description:string}) {return <div className={s.heading}><span className={s.number}>{number}</span><div><h2>{title}</h2><p>{description}</p></div></div>;}
export default function BusinessVerificationForm({details={}}:{details?:Record<string,string>}) {
  const listId=useId();const [country,setCountry]=useState(details.country??"");const [noPostal,setNoPostal]=useState(details.postal_code_not_applicable==="yes"&&details.country!=="India");
  const storedDial=[...countryCallingCodes].sort((a,b)=>b[1].length-a[1].length).find(([,dial])=>details.phone?.startsWith(dial));
  const initialPhoneCountry=details.phone_country??storedDial?.[0]??"";
  const initialPhone=details.phone_number??(storedDial?details.phone?.slice(storedDial[1].length):"");
  return <div className={s.form}><div className={s.intro}><span aria-hidden="true">▣</span><div><strong>One application for personal and business verification</strong><p>Your documents are private. An administrator reviews KYC and KYB before enabling B2B access.</p></div></div><BusinessActionForm action={submitBusinessApplication} button="Submit KYC & KYB application">
    <section className={s.section}><Heading number="01" title="Business profile" description="Enter your details as shown on your official business documents."/><div className={s.grid}><label className={s.field}>Registered business name *<input name="legal_name" required minLength={2} maxLength={160} autoComplete="organization" placeholder="Legal business name" defaultValue={details.legal_name}/></label><label className={s.field}>Legal entity type *<select name="entity_type" required defaultValue={details.entity_type??""}><option value="" disabled>Select legal entity</option>{["Sole proprietor","Company","Partnership / LLP","Other registered entity"].map(v=><option key={v}>{v}</option>)}</select></label><label className={s.field}>Registration / tax number *<input name="registration_number" required minLength={2} maxLength={100} placeholder="Business registration number or tax ID" defaultValue={details.registration_number}/></label><label className={s.field}>Country of registration *<input name="country" list={listId} required maxLength={100} autoComplete="country-name" placeholder="Start typing a country…" value={country} onChange={e=>{const next=e.target.value;setCountry(next);if(next==="India")setNoPostal(false);e.target.setCustomValidity(countryCallingCodes.some(([name])=>name===next)?"":"Choose a country from the suggestions.");}}/><datalist id={listId}>{countryCallingCodes.map(([name])=><option key={name} value={name}/>)}</datalist></label></div><fieldset className={s.purposeBlock}><legend className={s.purposeTitle}>Purpose of purchasing *</legend><div className={s.purposes}>{purchasingPurposes.map(([value,label,description])=><label key={value} className={s.purpose}><input type="radio" name="buyer_type" value={value} required defaultChecked={details.buyer_type===value}/><span><strong>{label}</strong><small>{description}</small></span></label>)}</div><p className={s.hint}>This describes your purchasing needs. Your Retailer or Reseller tier is calculated from monthly purchases; it is not selected here.</p></fieldset><label className={`${s.field} ${s.full}`} style={{marginTop:18}}>Business activity *<textarea name="activity" required minLength={2} maxLength={1000} rows={3} placeholder="Describe your business and the products you plan to purchase." defaultValue={details.activity}/></label></section>
    <section className={s.section}><Heading number="02" title="Registered business address" description="Use the address shown on your business address proof."/><div className={s.grid}><label className={`${s.field} ${s.full}`}>Address line 1 *<input name="address_line1" required minLength={3} maxLength={150} autoComplete="address-line1" placeholder="Building, house number and street" defaultValue={details.address_line1??details.address?.split("\n")[0]}/></label><label className={`${s.field} ${s.full}`}><span>Address line 2 <span className={s.optional}>(optional)</span></span><input name="address_line2" maxLength={150} autoComplete="address-line2" placeholder="Apartment, area or locality" defaultValue={details.address_line2}/></label><label className={s.field}>City / town *<input name="city" required maxLength={80} autoComplete="address-level2" defaultValue={details.city}/></label><label className={s.field}>State / province / region{country==="India"?" *":" (optional)"}<input name="state" required={country==="India"} maxLength={80} autoComplete="address-level1" defaultValue={details.state}/></label><label className={s.field}>PIN / postal code{noPostal?"":" *"}<input name="postal_code" required={!noPostal} disabled={noPostal} maxLength={16} minLength={2} autoComplete="postal-code" pattern={country==="India"?"[1-9][0-9]{5}":undefined} title={country==="India"?"Enter a six-digit Indian PIN code.":undefined} placeholder={country==="India"?"6-digit PIN code":"ZIP / postal code"} defaultValue={details.postal_code}/></label>{country!=="India"&&<label className={s.check} style={{alignSelf:"center"}}><input type="checkbox" name="postal_code_not_applicable" value="yes" checked={noPostal} onChange={e=>setNoPostal(e.target.checked)}/>My address does not use a postal code.</label>}</div></section>
    <section className={s.section}><Heading number="03" title="Authorized representative · KYC" description="Provide the details and personal documents of the person representing this business."/><div className={s.grid}><label className={s.field}>Full name as shown on photo ID *<input name="contact_name" required minLength={2} maxLength={120} autoComplete="name" placeholder="Representative's full legal name" defaultValue={details.contact_name}/></label><label className={s.field}>Role in the business *<select name="representative_role" required defaultValue={details.representative_role??""}><option value="" disabled>Select your role</option>{representativeRoles.map(role=><option key={role}>{role}</option>)}</select></label><div className={`${s.phone} ${s.full}`}><label className={s.field}>Phone country code *<select name="phone_country" required defaultValue={initialPhoneCountry} autoComplete="tel-country-code"><option value="" disabled>Select country code</option>{countryCallingCodes.map(([name,code])=><option key={name} value={name}>{name} ({code})</option>)}</select></label><label className={s.field}>Phone number *<input name="phone_number" type="tel" required minLength={4} maxLength={24} autoComplete="tel-national" placeholder="Number without country code" defaultValue={initialPhone}/></label></div><label className={s.field}>Photo ID document type *<select name="identity_document_type" required defaultValue={details.identity_document_type??""}><option value="" disabled>Select document type</option>{identityDocumentTypes.map(type=><option key={type}>{type}</option>)}</select></label></div><div className={s.uploads} style={{marginTop:20}}><Upload kind="identity"/><Upload kind="personal_address"/></div></section>
    <section className={s.section}><Heading number="04" title="Business documents · KYB" description="Help us verify the business, its registered address and ownership."/><label className={s.field}>Business owners and controlling persons *<textarea name="owners" required minLength={2} maxLength={2000} rows={3} placeholder="List each owner's full name and ownership percentage, and anyone who controls the business." defaultValue={details.owners}/></label><div className={s.uploads} style={{marginTop:20}}><Upload kind="registration"/><Upload kind="address"/><Upload kind="ownership"/></div></section>
    <label className={s.check}><input type="checkbox" name="consent" value="accepted" required/>I am authorized to represent this business. The personal and business information and documents provided are accurate, and I agree to their review for KYC and KYB verification.</label>
  </BusinessActionForm></div>;
}
