import Link from "@/components/NavigationLink";
import Form from "next/form";
import { Fragment } from "react";
import { portalCustomer, customerOrders, type PortalFilters } from "@/lib/business-portal-data";
import { portalDate, portalPage } from "@/lib/business-portal";
import { Pagination, Status } from "./Shared";
import s from "./Portal.module.css";
export default async function PortalOrders({searchParams}:{searchParams:Promise<PortalFilters>}) {
  const filters=await searchParams, page=portalPage(filters.page); const {email}=await portalCustomer();
  const result=await customerOrders(email,filters).range((page-1)*20,page*20-1);
  if(result.error) throw Error("Unable to load business orders. Please try again.");
  const query=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v&&k!=="page")query.set(k,v);query.set("kind","orders");
  return <><div className={s.titleLine}><h2>Order history</h2><div className={s.actions}><a className={s.button} href={`/account/portal/export?${query}`}>↓ Export orders (CSV)</a><Link className={s.primary} href="/account/portal/new" scroll={false}>＋ New order</Link></div></div><Form action="/account/portal" scroll={false} className={s.toolbar}><label className={s.search}>Order number<input name="q" defaultValue={filters.q} placeholder="Search current or old order number"/></label><label>From (India time)<input name="from" type="date" defaultValue={filters.from}/></label><label>To<input name="to" type="date" defaultValue={filters.to}/></label><label>Status<select name="status" defaultValue={filters.status??""}><option value="">All orders</option>{["DELIVERED","PAID","PROCESSING","PENDING_PAYMENT","PAYMENT_REVIEW","CANCELLED","REFUNDED"].map(v=><option key={v} value={v}>{v.replaceAll("_"," ")}</option>)}</select></label><button className={s.button}>Filter</button><Link className={s.button} href="/account/portal" scroll={false}>Reset</Link></Form><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Order / date (IST)</th><th>Product</th><th>Quantity</th><th>Status</th><th>Amount / actions</th></tr></thead><tbody>{result.data.map(order=><Fragment key={order.id}><tr className={s.orderRow}><td><Link className={s.link} href={`/account/portal/orders/${order.id}`}>{order.order_number}</Link><p className={s.muted}>{portalDate(order.created_at)}</p></td><td colSpan={2}>{order.order_items.length} item(s)</td><td><Status value={order.status}/></td><td><div className={s.money}>{new Intl.NumberFormat("en-US",{style:"currency",currency:order.currency}).format(Number(order.total))}</div><div className={s.actions}><Link className={s.link} href={`/account/portal/orders/${order.id}`}>View</Link><Link className={s.link} href={`/account/portal/orders/${order.id}/invoice`}>Invoice</Link></div></td></tr>{order.order_items.map(item=><tr key={item.id}><td/><td className={s.itemName}>{item.product_name}<p className={s.muted}>{item.option_name}</p></td><td>{item.quantity}</td><td/><td>{["PAID","PROCESSING","DELIVERED"].includes(order.status)&&<div className={s.actions}><a className={s.button} href={`/account/portal/export?kind=codes&order=${order.id}&item=${item.id}`}>CSV</a><a className={s.button} href={`/account/portal/export?kind=codes&order=${order.id}&item=${item.id}&format=txt`}>TXT</a></div>}</td></tr>)}</Fragment>)}</tbody></table>{!result.data.length&&<div className={s.empty}>No orders match your filters.</div>}</div><Pagination page={page} count={result.count??0} base="/account/portal" params={filters}/><p className={s.helper}>Code downloads contain delivered codes only. CSV files open in Excel.</p></>;
}
