import type { Metadata } from "next";
import PolicyPage from "../../components/PolicyPage";

export const metadata: Metadata = { title: "Privacy Policy" };

const EFFECTIVE_DATE = "13 August 2026";

export default function PrivacyPolicyPage() {
  return (
    <PolicyPage
      eyebrow="Your Privacy"
      title="Privacy Policy"
      summary="This policy explains how InGamePin, operated by AMAN G, collects, uses, shares and protects personal information."
      sections={[
        { title: "Effective date and who we are", content: <><p><strong>Effective date:</strong> {EFFECTIVE_DATE}</p><p>InGamePin is operated by AMAN G, GSTIN 19CMAPG4174K1ZV, at Chandpur Leningarh, near Jagorani Sangha Club, South Jogendra Nagar, Kolkata, West Bengal 700110, India. Privacy requests may be sent to <a href="mailto:support@ingamepin.com">support@ingamepin.com</a>.</p></> },
        { title: "Information we collect", content: <><ul><li>Identity and contact information supplied by you, such as name, email address, phone number, address and tax identification details.</li><li>Account, authentication, security-setting and customer-preference information.</li><li>Order data, including products, player ID, server or zone, platform, region, delivery status and delivered-content records.</li><li>Payment and verification data, including method, amount, provider references, transaction identifiers and wallet activity. We do not ask for private wallet keys or full payment credentials.</li><li>Affiliate applications, referrals, commissions, payout addresses and related fraud-prevention information.</li><li>Support and live-chat communications, complaints, screenshots and investigation records.</li><li>Device, browser, IP address, approximate location, referral, cookie and website-usage information.</li></ul></> },
        { title: "How and why we use information", content: <><p>We use information to provide accounts; accept, verify and deliver orders; complete top-ups; manage wallet and affiliate services; prevent fraud and abuse; communicate order, delivery, security and policy updates; provide support; issue invoices; maintain the website; comply with accounting, tax and legal duties; and establish or defend legal claims.</p><p>Depending on applicable law, processing is based on performance of a contract, legal obligations, legitimate interests such as security and service improvement, or consent.</p></> },
        { title: "Payments and digital assets", content: <><p>Payment transactions may be processed by Binance Pay, FreeKassa, Pally, blockchain networks or other providers shown at checkout. These providers handle information under their own terms. We receive the status and identifiers needed to verify and reconcile a transaction.</p><p>Wallet records include credits, debits, refunds and related order history. Public blockchain transactions may remain visible permanently on the applicable network.</p></> },
        { title: "Cookies and local storage", content: <><p>We use essential cookies and local storage for sessions, authentication, carts, preferences, affiliate attribution, security and checkout. Analytics or performance technologies may be used to improve reliability.</p><p>Blocking essential storage may prevent account, cart or checkout functions from working. Where required, consent will be requested before non-essential technologies are used.</p></> },
        { title: "Sharing and service providers", content: <><p>We share only information reasonably necessary with hosting, database, authentication, email, analytics, fraud-prevention, customer-support, payment, blockchain-monitoring, supplier, distributor, publisher and delivery providers. A player ID may be supplied to a fulfillment provider to complete a top-up.</p><p>We may disclose information when required by law, to protect rights and security, during a business reorganization, or at your direction. We do not sell personal information for money.</p></> },
        { title: "International processing", content: <><p>InGamePin serves customers internationally. Providers, publishers and suppliers may process information outside your country. Where required, we use appropriate contractual or legal safeguards, although other countries may have different data-protection laws.</p></> },
        { title: "Retention", content: <><p>We retain information only as long as reasonably necessary for orders, delivery, support, fraud prevention, disputes, and legal, tax or accounting obligations. Retention varies by record type. Data is then deleted, anonymized or securely isolated unless continued retention is required.</p><p>Blockchain records and records held independently by payment providers may not be erasable by InGamePin.</p></> },
        { title: "Security", content: <><p>We use reasonable administrative, technical and organizational safeguards, including access controls, encrypted connections, multi-factor authentication options and vetted service providers. No online system is completely secure. Protect your password, passkeys and authenticator codes and report suspected unauthorized access promptly.</p></> },
        { title: "Your choices and rights", content: <><p>Subject to applicable law, you may request access, correction, deletion, withdrawal of consent, or information about how your personal data is handled. We may verify identity before acting.</p><p>Information required for an active transaction, fraud prevention, accounting, tax, disputes or legal compliance may be retained where legally permitted or required.</p></> },
        { title: "Children", content: <><p>InGamePin is not intended for children who cannot legally consent to data processing or enter a contract. A parent or guardian should supervise purchases by minors. Contact us if you believe a child supplied information without proper authorization.</p></> },
        { title: "Updates and privacy contact", content: <><p>We may update this policy prospectively to reflect legal, service or operational changes. The effective date above will be updated when material changes are published.</p><p><strong>Grievance Officer:</strong> AMAN G<br /><strong>Email:</strong> <a href="mailto:support@ingamepin.com">support@ingamepin.com</a><br /><strong>WhatsApp:</strong> <a href="https://wa.me/919073045011">+91 90730 45011</a><br /><strong>Telegram:</strong> <a href="https://t.me/ingamepinsupport">@ingamepinsupport</a></p></> },
      ]}
    />
  );
}
