import type { Metadata } from "next";
import PolicyPage from "../../components/PolicyPage";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPolicyPage() {
  return <PolicyPage eyebrow="Your Privacy" title="Privacy Policy" summary="This policy explains how InGamePin, operated by AMAN G, collects, uses, shares and protects personal information when you use our digital gaming store." sections={[
    { title: "Who we are", content: <><p>InGamePin is a digital gaming store operated by AMAN G. AMAN G is responsible for the personal information described in this policy. Questions and privacy requests may be sent to <a href="mailto:support@ingamepin.com">support@ingamepin.com</a>.</p></> },
    { title: "Information we collect", content: <><ul><li>Identity and contact information, such as name, email address and phone number.</li><li>Account information, login records and customer preferences.</li><li>Order data, including products, player ID, server or zone, platform, region and delivery status.</li><li>Payment and verification data, such as payment method, amount, UPI or Binance Pay transaction reference, wallet activity and limited proof of payment. Payment providers process sensitive credentials; we do not need your UPI PIN, OTP, private key or full card credentials.</li><li>Support communications, complaints, screenshots and investigation records.</li><li>Device, browser, IP address, approximate location, referral, cookie and usage information.</li></ul></> },
    { title: "How we use information", content: <><p>We use information to create and secure accounts; accept, verify and deliver orders; perform player-ID top-ups; deliver and support codes; manage InGamePin Wallet balances; detect fraud and abuse; communicate order and policy updates; provide customer service; maintain and improve the website; comply with accounting, tax and legal obligations; and establish or defend legal claims.</p><p>We process information where necessary to perform a contract, comply with law, pursue legitimate interests such as security and service improvement, or with consent where required.</p></> },
    { title: "Payments", content: <><p>UPI, Binance Pay and other payment transactions may be processed by banks, payment networks, cryptocurrency payment providers or other service providers under their own privacy terms. We receive transaction status and identifiers needed to verify payment and reconcile orders.</p><p>InGamePin Wallet records include credits, debits, refunds and related order history so we can operate and secure the wallet service.</p></> },
    { title: "Cookies and similar technology", content: <><p>We may use essential cookies and local storage for sessions, authentication, carts, preferences, security and checkout. We may also use analytics or performance technologies to understand website use and improve reliability.</p><p>You can manage cookies through your browser. Blocking essential storage may prevent account, cart or checkout functions from working. Where required, we will request consent before using non-essential cookies.</p></> },
    { title: "Sharing and service providers", content: <><p>We may share only the information reasonably necessary with hosting, database, authentication, email, analytics, fraud-prevention, customer-support, payment, supplier, distributor, publisher and delivery providers. For example, a player ID may be provided to a fulfillment supplier to complete a top-up.</p><p>We may also disclose information to authorities or advisers when required by law, to protect rights and security, in connection with a business reorganization, or with your direction. We do not sell personal information for money.</p></> },
    { title: "International processing", content: <><p>Some providers, publishers or suppliers may process information outside your state or country. Where required, we use appropriate contractual or legal safeguards, while recognizing that other locations may have different data-protection laws.</p></> },
    { title: "Retention", content: <><p>We retain personal information only as long as reasonably necessary for orders, support, security, disputes and legal, tax or accounting duties. Retention varies by record type. We then delete, anonymize or securely isolate information unless continued retention is legally required.</p></> },
    { title: "Security", content: <><p>We use reasonable administrative, technical and organizational safeguards, including access controls and secure service providers. No online system is completely secure, so we cannot guarantee absolute security. Protect your password and promptly report suspected unauthorized access.</p></> },
    { title: "Your choices and rights", content: <><p>Subject to applicable law, you may request access, correction, deletion or information about the handling of your personal data, withdraw consent, or object to certain processing. We may verify identity before acting and may retain information where legally permitted or required.</p><p>Account and order records needed for an active transaction, fraud prevention or legal compliance may not be immediately deletable. Non-waivable privacy and consumer rights remain unaffected.</p></> },
    { title: "Children", content: <><p>InGamePin is not intended for children who cannot legally consent to data processing or contract under applicable law. A parent or guardian should supervise purchases by minors. Contact us if you believe a child provided personal information without proper authorization.</p></> },
    { title: "Updates and contact", content: <><p>We may update this policy to reflect service, legal or operational changes. The revised policy applies prospectively from the date posted.</p><p><strong>Grievance Officer:</strong> AMAN G<br /><strong>Operator:</strong> AMAN G<br /><strong>Email:</strong> <a href="mailto:support@ingamepin.com">support@ingamepin.com</a></p></> },
  ]} />;
}
