"use client";
import {useState} from "react";
import {submitPartnerApplication} from "./actions";
import {supplierFields} from "@/lib/supplier-application";
export default function PartnerApplicationForm(){const [partnerType,setPartnerType]=useState("");return (
          <form action={submitPartnerApplication} className="mt-7 grid gap-5 sm:grid-cols-2">
            <input name="company_site" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true" />
            <label className="font-bold">Partnership type<select name="partner_type" value={partnerType} onChange={event => setPartnerType(event.target.value)} required className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3"><option value="">Select an option</option><option value="PAYMENT_PROVIDER">Payment provider</option><option value="GAMING_DISTRIBUTOR">Gaming distributor / product supplier</option></select></label>
            <label className="font-bold">Company name<input name="company" required minLength={2} maxLength={120} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>
            <label className="font-bold">Contact person<input name="contact_name" required minLength={2} maxLength={100} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>
            <label className="font-bold">Business email<input name="email" type="email" required maxLength={160} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>
            <label className="font-bold">Company website<input name="website" type="url" placeholder="https://" maxLength={250} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>
            <label className="font-bold">Country / region<input name="country" required minLength={2} maxLength={100} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>
            {partnerType === "GAMING_DISTRIBUTOR" && <fieldset className="grid gap-5 rounded-2xl border border-white/15 p-4 sm:col-span-2 sm:grid-cols-2"><legend className="px-2 text-lg font-bold text-cyan-300">Supply products to iNgamePIN</legend><p className="text-sm text-slate-300 sm:col-span-2">Tell us what you can supply for resale through our website, including your authorization and wholesale terms.</p>{supplierFields.map(field => <label key={field.name} className="font-bold sm:col-span-2">{field.label}{!field.required && <span className="font-normal text-slate-400"> (optional)</span>}{field.options ? <select name={field.name} required={field.required} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3"><option value="">Select an option</option>{field.options.map(option=><option key={option} value={option}>{option}</option>)}</select> : field.name === "catalogue_url" ? <input name={field.name} type="url" maxLength={field.maxLength} placeholder={field.placeholder} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3"/> : <textarea name={field.name} required={field.required} minLength={field.required?2:undefined} maxLength={field.maxLength} rows={2} placeholder={field.placeholder} className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3"/>}</label>)}</fieldset>}
            {partnerType !== "GAMING_DISTRIBUTOR" && <label className="font-bold sm:col-span-2">Estimated monthly volume <span className="font-normal text-slate-400">(optional)</span><input name="monthly_volume" maxLength={100} placeholder="Transactions, orders or inventory value" className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>}
            <label className="font-bold sm:col-span-2">{partnerType === "GAMING_DISTRIBUTOR" ? "Additional proposal details (optional)" : "Proposal"}<textarea name="proposal" required={partnerType !== "GAMING_DISTRIBUTOR"} minLength={partnerType === "GAMING_DISTRIBUTOR" ? undefined : 20} maxLength={3000} rows={6} placeholder="Describe your services or product catalogue, supported regions, wholesale pricing, minimum order quantities, delivery options and commercial terms." className="mt-2 w-full rounded-xl border border-white/15 bg-slate-900 px-4 py-3" /></label>
            <label className="flex items-start gap-3 text-sm text-slate-300 sm:col-span-2"><input type="checkbox" name="consent" value="yes" required className="mt-1 h-4 w-4 accent-cyan-400" />I am authorized to contact InGamePin for this company and agree that the submitted information may be used to review this proposal.</label>
            <button className="rounded-xl bg-cyan-400 px-7 py-3.5 font-black text-slate-950 hover:bg-cyan-300 sm:col-span-2">Send partnership proposal</button>
          </form>
);}
