import Link from "@/components/NavigationLink";
import Form from "next/form";
import { portalCustomer, customerStatement, type PortalFilters } from "@/lib/business-portal-data";
import { portalDate, portalPage, usd } from "@/lib/business-portal";
import { Pagination } from "../Shared";
import s from "../Portal.module.css";
export default async function Statement({searchParams}:{searchParams:Promise<PortalFilters>}) {
  const filters=await searchParams, page=portalPage(filters.page), {user}=await portalCustomer();
  const result=await customerStatement(user.id,filters).range((page-1)*20,page*20-1);
  if(result.error)throw Error("Unable to load wallet statement.");
  const query=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v&&k!=="page")query.set(k,v);query.set("kind","statement");
  return <><div className={s.titleLine}><h2>Wallet statement</h2><a className={s.button} href={`/account/portal/export?${query}`}>↓ Download statement (CSV)</a></div><Form action="/account/portal/statement" scroll={false} className={s.toolbar}><label>Currency<select aria-label="Statement currency"><option>US Dollar · USD</option></select></label><label>From (India time)<input type="date" name="from" defaultValue={filters.from}/></label><label>To<input type="date" name="to" defaultValue={filters.to}/></label><label>Activity<select name="type" defaultValue={filters.type??""}><option value="">All activity</option><option value="DEBIT">Debits</option><option value="CREDIT">Credits / payments</option></select></label><button className={s.button}>Filter</button><Link className={s.button} href="/account/portal/statement" scroll={false}>Reset</Link></Form><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Date (IST)</th><th>Type</th><th>Description / reference</th><th>Debit</th><th>Credit</th><th>Balance</th><th>Order</th></tr></thead><tbody>{result.data.map(row=><tr key={row.id}><td>{portalDate(row.created_at)}</td><td>{row.transaction_type}</td><td>{row.description}<p className={s.muted}>{row.reference_id??row.id}</p></td><td className={s.money}>{row.transaction_type==="DEBIT"?usd(row.amount):"—"}</td><td className={s.money}>{row.transaction_type!=="DEBIT"?usd(row.amount):"—"}</td><td className={s.money}>{usd(row.balance_after)}</td><td>{row.order_id&&<Link className={s.link} href={`/account/portal/orders/${row.order_id}/invoice`}>Invoice ↗</Link>}</td></tr>)}</tbody></table>{!result.data.length&&<div className={s.empty}>No wallet activity matches your filters.</div>}</div><Pagination page={page} count={result.count??0} base="/account/portal/statement" params={filters}/><p className={s.helper}>One shared wallet for retail and business. This statement includes activity from both portals; the balance is recorded after each transaction.</p></>;
}
