"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";

import {
  useStorePreferences,
  type StoreLanguage,
} from "./StorePreferences";

const russianText: Record<string, string> = {
  "Return to dashboard": "Вернуться в личный кабинет",
  "← Return to dashboard": "← Вернуться в личный кабинет",
  "Available balance": "Доступный баланс",
  "USD wallet": "USD-кошелёк",
  "Add money": "Пополнить кошелёк",
  "Choose an amount and pay using any available gateway.":
    "Выберите сумму и оплатите через любой доступный способ.",
  "Add money through any available payment gateway.":
    "Пополняйте баланс через любой доступный способ оплаты.",
  "Your balance is credited automatically after verified payment.":
    "Баланс пополняется автоматически после подтверждения платежа.",
  "Top-up amount (USD)": "Сумма пополнения (USD)",
  "Minimum amount: $10": "Минимальная сумма: $10",
  "Payment method": "Способ оплаты",
  "Instant verification": "Мгновенное подтверждение",
  "Cards and local methods": "Карты и местные способы оплаты",
  "Available payment methods": "Доступные способы оплаты",
  "Add amount": "Сумма пополнения",
  "New balance": "Новый баланс",
  "Minimum wallet top-up: $10. New configured gateway adapters appear here automatically.":
    "Минимальное пополнение кошелька: $10. Новые способы оплаты появляются здесь автоматически.",
  "Continue to payment": "Перейти к оплате",
  "Bulk delivery information": "Информация об оптовой доставке",
  "Bulk Delivery Time: 1-15 Working Days": "Срок оптовой доставки: 1–15 рабочих дней",
  "Please confirm that you understand the delivery time.":
    "Подтвердите, что вы понимаете срок доставки.",
  "I understand": "Понятно",
  "Your cart contains a bulk delivery product. Confirm before continuing to payment.":
    "В вашей корзине есть товар с оптовой доставкой. Подтвердите это перед переходом к оплате.",
  "Cancel": "Отмена",
  "Opening payment gateway...": "Открываем платёжную систему...",
  "Recent top-ups": "Недавние пополнения",
  "No top-ups yet.": "Пополнений пока нет.",
  "Welcome back": "С возвращением",
  "Sign in to manage your orders, wallet and profile.":
    "Войдите, чтобы управлять заказами, кошельком и профилем.",
  "Customer account": "Аккаунт покупателя",
  "Email address": "Адрес электронной почты",
  Password: "Пароль",
  "Sign in": "Войти",
  "Forgot password?": "Забыли пароль?",
  "New customer?": "Новый покупатель?",
  "Create account": "Создать аккаунт",
  "Create your account": "Создайте аккаунт",
  "Already have an account?": "Уже есть аккаунт?",
  "Enter your OTP": "Введите код",
  "Verify & Activate Account": "Подтвердить и активировать аккаунт",
  "Resend verification code": "Отправить код повторно",
  "Use a different email address": "Использовать другой email",
  "My orders": "Мои заказы",
  "My codes": "Мои коды",
  "My wallet": "Мой кошелёк",
  Profile: "Профиль",
  "Sign out": "Выйти",
  "Wallet balance": "Баланс кошелька",
  "Delivered codes": "Полученные коды",
  Notifications: "Уведомления",
  "Account details": "Данные аккаунта",
  "Full name": "Полное имя",
  Phone: "Телефон",
  "Save profile": "Сохранить профиль",
  "Shopping Cart": "Корзина",
  "Your cart is empty.": "Ваша корзина пуста.",
  "Continue shopping": "Продолжить покупки",
  Product: "Товар",
  Price: "Цена",
  Quantity: "Количество",
  Subtotal: "Промежуточный итог",
  Discount: "Скидка",
  Delivery: "Доставка",
  Taxes: "Налоги",
  "Total Amount": "Итоговая сумма",
  "Remove": "Удалить",
  "Clear cart": "Очистить корзину",
  "Proceed to checkout": "Перейти к оформлению",
  "Secure order processing": "Безопасное оформление заказа",
  "Complete your details and choose a payment method.":
    "Заполните данные и выберите способ оплаты.",
  "Billing details": "Данные покупателя",
  "Customer name": "Имя покупателя",
  "Email for delivery": "Email для доставки",
  "Phone number": "Номер телефона",
  "Delivery Method": "Способ доставки",
  "Payment Method": "Способ оплаты",
  "Order Note": "Примечание к заказу",
  "Optional delivery instructions.": "Дополнительные инструкции по доставке.",
  "Continue to Payment": "Перейти к оплате",
  "Your information is securely processed":
    "Ваши данные обрабатываются безопасно",
  "I agree to the Terms, privacy policy and applicable returns or replacement policy.":
    "Я принимаю Условия, политику конфиденциальности и правила возврата или замены.",
  "Payment unavailable": "Оплата недоступна",
  "Return to checkout": "Вернуться к оформлению",
  "Order total": "Сумма заказа",
  "Pay securely with PayPalych": "Безопасная оплата через PayPalych",
  "Continue to PayPalych": "Перейти к PayPalych",
  "Pay with USDT": "Оплатить USDT",
  "Direct wallet payment": "Прямая оплата на кошелёк",
  "Your payment is verified automatically on the blockchain.":
    "Платёж автоматически проверяется в блокчейне.",
  "Select the network you will send from": "Выберите сеть отправки",
  "Solana network": "\u0421\u0435\u0442\u044c Solana",
  Network: "Сеть",
  "Send exactly": "Отправьте точно",
  "Receiving address": "Адрес получателя",
  "Copy address": "Копировать адрес",
  "I have sent the payment": "Я отправил платёж",
  "Invoice expires in": "Счёт истекает через",
  "Payment detected": "Платёж обнаружен",
  "Waiting for blockchain confirmation...":
    "Ожидаем подтверждение в блокчейне...",
  "Contact Support": "Связаться с поддержкой",
  "How can we help?": "Чем мы можем помочь?",
  "Get help with orders, payments, delivery and your account.":
    "Получите помощь по заказам, оплате, доставке и аккаунту.",
  "Telegram Support": "Поддержка в Telegram",
  "Message us on Telegram": "Написать нам в Telegram",
  "WhatsApp Support": "Поддержка в WhatsApp",
  "Message us on WhatsApp": "Написать нам в WhatsApp",
  "Support hours": "Часы поддержки",
  "Frequently asked questions": "Часто задаваемые вопросы",
  "Track your order": "Отследить заказ",
  "Enter your order number and email address to check its status.":
    "Введите номер заказа и email, чтобы проверить статус.",
  "Order number": "Номер заказа",
  "Check status": "Проверить статус",
  "Order status": "Статус заказа",
  Status: "Статус",
  Date: "Дата",
  Amount: "Сумма",
  "Order items": "Товары в заказе",
  Browse: "Каталог",
  "Featured Products": "Рекомендуемые товары",
  "Popular Categories": "Популярные категории",
  "Explore game credits, keys, gift cards and subscriptions.":
    "Игровая валюта, ключи, подарочные карты и подписки.",
  "Player-ID top-ups and gaming vouchers":
    "Пополнения по ID игрока и игровые ваучеры",
  "Fixed-value and custom-value gift cards":
    "Подарочные карты фиксированного и произвольного номинала",
  "Digital subscription plans and vouchers":
    "Цифровые подписки и ваучеры",
  "Game editions and activation keys":
    "Издания игр и ключи активации",
  "View Products": "Смотреть товары",
  "View Products →": "Смотреть товары →",
  "View Gaming Top-Ups": "Смотреть товары для пополнения игр",
  "View Gift Cards": "Смотреть подарочные карты",
  "View Subscriptions": "Смотреть подписки",
  "View Game Keys": "Смотреть игровые ключи",
  "Best Sellers": "Хиты продаж",
  "Popular products selected for InGamePin customers.":
    "Популярные товары, отобранные для покупателей InGamePin.",
  "For resellers & businesses": "Для реселлеров и бизнеса",
  "Need products in bulk quantity?": "Нужны товары оптом?",
  "Explore bulk products with flexible quantities, competitive B2B pricing and dedicated support.":
    "Ознакомьтесь с оптовыми товарами, гибкими объёмами, выгодными B2B-ценами и персональной поддержкой.",
  "View B2B Bulk Products": "Смотреть оптовые товары B2B",
  "B2B Bulk Products": "Оптовые товары B2B",
  "B2B Bulk": "B2B Оптом",
  "Bulk digital products for resellers and businesses with flexible quantities and dedicated support.":
    "Оптовые цифровые товары для реселлеров и бизнеса с гибкими объёмами и персональной поддержкой.",
  "No active products are available in this collection yet.":
    "В этой оптовой категории пока нет доступных товаров.",
  "View all": "Смотреть все",
  "Shop now": "Купить сейчас",
  "Digital Delivery": "Цифровая доставка",
  "Instant Delivery": "Мгновенная доставка",
  "UID Required": "Требуется UID",
  "Share products. Earn commission in USDT.":
    "Делитесь товарами. Получайте комиссию в USDT.",
  "Create referral links for eligible products and earn from approved customer orders.":
    "Создавайте реферальные ссылки на доступные товары и получайте доход с подтверждённых заказов.",
  "Browse Store": "Каталог магазина",
  "Search the store or choose a product category.":
    "Найдите товар или выберите категорию.",
  "Search results for:": "Результаты поиска:",
  "Clear search": "Очистить поиск",
  "In Stock Only": "Только в наличии",
  "Sort by": "Сортировка",
  "Sort products": "Сортировать товары",
  Featured: "Рекомендуемые",
  "Price: Low to High": "Цена: по возрастанию",
  "Price: High to Low": "Цена: по убыванию",
  "Best Selling": "Самые продаваемые",
  "Highest Rated": "С высоким рейтингом",
  "Player-ID top-ups and gaming voucher products.":
    "Пополнения по ID игрока и игровые ваучеры.",
  "Fixed-value and custom-value digital gift cards.":
    "Цифровые подарочные карты фиксированного и произвольного номинала.",
  "Digital membership plans and subscription vouchers.":
    "Цифровые подписки и ваучеры.",
  "Game editions and activation keys for supported platforms.":
    "Издания игр и ключи активации для поддерживаемых платформ.",
  "Show Fewer Products": "Показать меньше товаров",
  "No products found": "Товары не найдены",
  "Change the search, category or availability filter.":
    "Измените запрос, категорию или фильтр наличия.",
  "No products found.": "Товары не найдены.",
  "Accepted payment methods": "Принимаемые способы оплаты",
  "Secure payments": "Безопасные платежи",
  "Automatic verification": "Автоматическое подтверждение",
  "Secure payments • Automatic verification":
    "Безопасная оплата • Автоматическое подтверждение",
  "Faster Payment System": "Система быстрых платежей",
  "Live Chat": "Онлайн-чат",
  "InGamePin Support": "Поддержка InGamePin",
  "We usually reply shortly": "Обычно мы отвечаем быстро",
  "Start chat": "Начать чат",
  Name: "Имя",
  Email: "Email",
  Message: "Сообщение",
  Send: "Отправить",
  "Close chat": "Закрыть чат",
  "Type your message...": "Введите сообщение...",
  "Terms & Conditions": "Условия использования",
  "Return & Refund Policy": "Политика возврата средств",
  "Privacy Policy": "Политика конфиденциальности",
  "Terms of Use": "Условия использования",
  "Returns and Refunds": "Возвраты и возмещения",
  "Last updated": "Последнее обновление",
  "Back to store": "Вернуться в магазин",
  "Different products": "Разные товары",
  "Total quantity": "Общее количество",
  "Your product discounts": "Ваши скидки на товары",
  "USDT network": "Сеть USDT",
  "Top-up pending": "Пополнение ожидает подтверждения",
  "Top-up requests": "Заявки на пополнение",
  "No wallet top-up requests yet.": "Заявок на пополнение пока нет.",
  "Wallet transactions": "Операции кошелька",
  "No wallet transactions yet.": "Операций по кошельку пока нет.",
  "Wallet": "Кошелёк",
  "Customer": "Покупатель",
  "Overview": "Обзор",
  "My account": "Мой аккаунт",
  "Manage purchases, codes, notifications and wallet balance.": "Управляйте покупками, кодами, уведомлениями и балансом кошелька.",
  "Add money or view transactions →": "Пополнить баланс или посмотреть операции →",
  "Total orders": "Всего заказов",
  "Available securely below": "Доступно в защищённом разделе ниже",
  "Newest purchases appear first.": "Новые покупки отображаются первыми.",
  "Track an order": "Отследить заказ",
  "No orders found for this email address.": "Заказы для этого адреса электронной почты не найдены.",
  "Products": "Товары",
  "My delivered codes": "Мои полученные коды",
  "Keep codes private and redeem them only on the official platform.": "Храните коды в тайне и активируйте их только на официальной платформе.",
  "No delivered digital codes yet.": "Полученных цифровых кодов пока нет.",
  "Delivered": "Доставлено",
  "No notifications yet.": "Уведомлений пока нет.",
  "Not added": "Не добавлено",
  "Email status": "Статус email",
  "Verified": "Подтверждён",
  "Welcome to InGamePin": "Добро пожаловать в InGamePin",
  "Sign in to track orders, access delivered codes and manage your wallet.": "Войдите, чтобы отслеживать заказы, получать коды и управлять кошельком.",
  "Login": "Вход",
  "Reset password": "Сбросить пароль",
  "We will send a secure reset link to your email.": "Мы отправим безопасную ссылку для сброса пароля на ваш email.",
  "Send reset link": "Отправить ссылку для сброса",
  "Return to login": "Вернуться ко входу",
  "Choose new password": "Выберите новый пароль",
  "New password": "Новый пароль",
  "Confirm password": "Подтвердите пароль",
  "Update password": "Обновить пароль",
  "Add money to your wallet": "Пополнить кошелёк",
  "Binance calculates the supported cryptocurrency amount from your USD top-up.": "Binance рассчитает сумму поддерживаемой криптовалюты из суммы пополнения в USD.",
  "Wallet top-up": "Пополнение кошелька",
  "Cancel and return to wallet": "Отменить и вернуться в кошелёк",
  "Monday - Sunday": "Понедельник — воскресенье",
  "Response Time": "Время ответа",
  "Usually 5–15 mins": "Обычно 5–15 минут",
  "Language": "Язык",
  "English, Hindi, Bengali": "Английский, хинди, бенгальский",
  "Select state": "Выберите штат",
  "Balance": "Баланс",
  "Digital Email Delivery": "Цифровая доставка по email",
  "Delivery instructions will be sent to your email.": "Инструкции по доставке будут отправлены на ваш email.",
  "FREE": "БЕСПЛАТНО",
  "Pay securely with Binance": "Безопасная оплата через Binance",
  "Pay with USDT on TRC20, BEP20, or Solana": "\u041e\u043f\u043b\u0430\u0442\u0430 USDT \u0432 \u0441\u0435\u0442\u044f\u0445 TRC20, BEP20 \u0438\u043b\u0438 Solana",
  "Cards and other payment methods": "Карты и другие способы оплаты",
  "Faster Payments System or USDT": "Система быстрых платежей или USDT",
  "Insufficient wallet balance": "Недостаточно средств в кошельке",
  "Sign in to use your wallet": "Войдите, чтобы использовать кошелёк",
  "Included": "Включено",
  "Secure": "Безопасно",
  "Genuine": "Оригинальные товары",
  "Support": "Поддержка",
  "Trending Now": "Сейчас популярно",
  "Find Your Product": "Найдите свой товар",
  "Explore Products": "Смотреть товары",
  "Browse all products": "Все товары",
  "View product": "Открыть товар",
  "From": "От",
  "In stock": "В наличии",
  "Out of stock": "Нет в наличии",
  "Choose your product option": "Выберите вариант товара",
  "Select product option": "Выберите вариант товара",
  "Selected option": "Выбранный вариант",
  "Add to Cart": "Добавить в корзину",
  "Buy Now": "Купить сейчас",
  "Secure checkout": "Безопасное оформление",
  "Product Description": "Описание товара",
  "Game Features": "Особенности игры",
  "Region": "Регион",
  "Digital Product": "Цифровой товар",
  "Required customer information": "Необходимые данные покупателя",
  "Complete the required information for this product.": "Заполните обязательные данные для этого товара.",
  "Enter your details": "Введите данные",
  "Order summary": "Сводка заказа",
  "Place Order": "Оформить заказ",
  "Processing order...": "Обрабатываем заказ...",
  "Creating payment...": "Создаём платёж...",
  "Payment successful": "Оплата прошла успешно",
  "Your order has been paid successfully.": "Ваш заказ успешно оплачен.",
  "Continue": "Продолжить",
  "Back": "Назад",
  "Copy": "Копировать",
  "Copied": "Скопировано",
  "Loading...": "Загрузка...",
  "Please wait...": "Пожалуйста, подождите...",
  "Try again": "Попробовать снова",
  "Something went wrong.": "Что-то пошло не так.",
  "Payment failed": "Ошибка оплаты",
  "The payment was cancelled or could not be completed.": "Платёж был отменён или не удалось его завершить.",
  "Return to cart": "Вернуться в корзину",
  "Order completed": "Заказ завершён",
  "Thank you for your order.": "Спасибо за ваш заказ.",
  "Track Order": "Отследить заказ",
  "Search": "Найти",
  "Search products": "Поиск товаров",
  "All Products": "Все товары",
  "Home": "Главная",
  "Cart": "Корзина",
  "My Account": "Мой аккаунт",
  "Preorder": "Предзаказ",
  "Preorder Now": "Оформить предзаказ",
  "Preorder price": "Цена предзаказа",
  "Launches In": "До выхода",
  "Days": "Дней",
  "Hours": "Часов",
  "Min": "Мин",
  "Sec": "Сек",
  "Maybe Later": "Может быть позже",
  "Customer information": "Данные покупателя",
  "Submit preorder": "Оформить предзаказ",
  "Secure your preorder": "Оформите безопасный предзаказ",
  "Direct USDT": "Прямой платёж USDT",
  "PayPalych": "PayPalych",
  "FreeKassa": "FreeKassa",
  "Binance Pay": "Binance Pay",
  "My Orders": "Мои заказы",
  "My Codes": "Мои коды",
  "Affiliate": "Партнёрская программа",
  "Affiliate Program": "Партнёрская программа",
  "View and track every purchase.": "Просматривайте и отслеживайте все покупки.",
  "Order, payment, and account updates.": "Обновления заказов, платежей и аккаунта.",
  "Delivered content": "Доставленные товары",
  "Customer details": "Данные покупателя",
  "Payment details": "Данные платежа",
  "Download All Codes (.txt)": "Скачать все коды (.txt)",
  "Download Product Codes": "Скачать коды товара",
  "Secure digital delivery": "Безопасная цифровая доставка",
  "Keep these codes private. Each code can normally be redeemed only once.":
    "Храните эти коды в тайне. Обычно каждый код можно активировать только один раз.",
  "Verified purchase": "Подтверждённая покупка",
  "How was your purchase?": "Как прошла ваша покупка?",
  "Positive": "Положительный",
  "Negative": "Отрицательный",
  "Optional comment about your purchase": "Необязательный комментарий о покупке",
  "Submitting...": "Отправка...",
  "Submit review": "Отправить отзыв",
  "Verified reviews": "Подтверждённые отзывы",
  "Positive / Negative": "Положительные / Отрицательные",
  "No verified reviews yet": "Подтверждённых отзывов пока нет",
  "Customers can review this product after a completed delivery.":
    "Покупатели могут оставить отзыв после завершения доставки.",
  "Description": "Описание",
  "Reviews": "Отзывы",
  "Delivery instructions": "Инструкции по доставке",
  "Generate invoice": "Создать счёт",
  "Invoice": "Счёт",
  "Invoice ready": "Счёт готов",
  "Full legal name": "Полное юридическое имя",
  "Country": "Страна",
  "Complete billing address": "Полный платёжный адрес",
  "House/building, street, city, state, postal code":
    "Дом/строение, улица, город, регион, почтовый индекс",
  "Tax ID / TIN": "Налоговый номер / ИНН",
  "Product / denomination": "Товар / номинал",
  "Qty": "Кол-во",
  "Rate": "Цена",
  "Total": "Итого",
  "This is a computer-generated invoice.": "Это автоматически сформированный счёт.",
  "Protect your account with a Passkey": "Защитите аккаунт с помощью ключа доступа",
  "Sign in securely using your phone, fingerprint, face or device PIN.":
    "Безопасно входите с помощью телефона, отпечатка пальца, распознавания лица или PIN-кода устройства.",
  "Account protection": "Защита аккаунта",
  "Security": "Безопасность",
  "Use a Passkey to sign in without Google Authenticator codes.":
    "Используйте ключ доступа для входа без кодов Google Authenticator.",
  "Passkeys": "Ключи доступа",
  "Loading passkeys...": "Загрузка ключей доступа...",
  "No passkey is connected yet.": "Ключ доступа ещё не подключён.",
  "Enable Passkey": "Включить ключ доступа",
  "Add Passkey": "Добавить ключ доступа",
  "Sign in with Passkey": "Войти с ключом доступа",
  "Checking passkey...": "Проверка ключа доступа...",
  "Customer App Installed": "Приложение покупателя установлено",
  "Install Customer App": "Установить приложение покупателя",
  "Promote digital products. Earn commission in USDT.":
    "Продвигайте цифровые товары. Получайте комиссию в USDT.",
  "Join Affiliate Program": "Вступить в партнёрскую программу",
  "Learn & Join": "Узнать и присоединиться",
  "Ready to become a partner?": "Готовы стать партнёром?",
  "Apply": "Подать заявку",
  "Create links": "Создавайте ссылки",
  "Promote": "Продвигайте",
  "Earn USDT": "Получайте USDT",
  "Affiliate code": "Партнёрский код",
  "Promotion channel": "Канал продвижения",
  "Commission": "Комиссия",
  "Affiliate application": "Заявка в партнёрскую программу",
  "Update application": "Обновить заявку",
  "Affiliate applications are currently closed.": "Приём заявок в партнёрскую программу временно закрыт.",
  "Your application is waiting for administrator review.":
    "Ваша заявка ожидает проверки администратором.",
  "Fast Delivery": "Быстрая доставка",
  "Genuine Products": "Оригинальные товары",
  "Secure Checkout": "Безопасное оформление",
  "Customer Support": "Поддержка покупателей",
  "Receive digital products after payment verification and secure manual fulfillment.":
    "Получайте цифровые товары после подтверждения оплаты и безопасной ручной обработки.",
  "Products sourced from trusted and verified suppliers.":
    "Товары от надёжных и проверенных поставщиков.",
  "Protected order processing and secure private-code delivery.":
    "Защищённая обработка заказов и безопасная доставка личных кодов.",
  "Get assistance with orders, payments and redemption.":
    "Получите помощь с заказами, оплатой и активацией.",
  "Featured Product": "Рекомендуемый товар",
  "Game Preorder": "Предзаказ игры",
  "Preorder Price": "Цена предзаказа",
  "VIEW PRODUCT": "ОТКРЫТЬ ТОВАР",
  "PREORDER NOW": "ОФОРМИТЬ ПРЕДЗАКАЗ",
  "Available now": "Уже доступно",
  "Close preorder popup": "Закрыть окно предзаказа",
  "Previous slide": "Предыдущий слайд",
  "Next slide": "Следующий слайд",
  "Enter other amount": "Введите другую сумму",
  "Enter recipient email address": "Введите email получателя",
  "Decrease quantity": "Уменьшить количество",
  "Increase quantity": "Увеличить количество",
  "House number, building and street": "Номер дома, строение и улица",
  "Area, colony or locality": "Район или населённый пункт",
  "Nearby landmark": "Ближайший ориентир",
  "Enter city": "Введите город",
  "Payment gateway fee": "Комиссия платёжной системы",
  "Close live chat": "Закрыть онлайн-чат",
  "Your name": "Ваше имя",
  "Your email": "Ваш email",
  "Open live support chat": "Открыть чат поддержки",
  "Main navigation": "Основная навигация",
  "Mobile navigation": "Мобильная навигация",
  "Currency": "Валюта",
  "Mobile number": "Номер телефона",
  "Country calling code": "Телефонный код страны",
  "Loading payment...": "Загрузка платежа...",
  "Digital product": "Цифровой товар",
  "PENDING PAYMENT": "ОЖИДАЕТ ОПЛАТЫ",
  "PAYMENT REVIEW": "ПРОВЕРКА ПЛАТЕЖА",
  PENDING: "ОЖИДАЕТ",
  PENDING_PAYMENT: "ОЖИДАЕТ ОПЛАТЫ",
  PAYMENT_REVIEW: "ПРОВЕРКА ПЛАТЕЖА",
  SUBMITTED: "ОТПРАВЛЕН",
  PAID: "ОПЛАЧЕН",
  VERIFIED: "ПОДТВЕРЖДЁН",
  PROCESSING: "ОБРАБАТЫВАЕТСЯ",
  DELIVERED: "ДОСТАВЛЕН",
  COMPLETED: "ЗАВЕРШЁН",
  FAILED: "ОШИБКА",
  CANCELLED: "ОТМЕНЁН",
  REJECTED: "ОТКЛОНЁН",
  REFUNDED: "ВОЗВРАЩЁН",
  EXPIRED: "ИСТЁК",
  Checkout: "Оформление заказа",
  "Contact Information": "Контактная информация",
  "Used for order updates and delivery communication.": "Используется для обновлений заказа и связи по доставке.",
  "Order Summary": "Итог заказа",
  "Delivery email": "Email для доставки",
  "In Stock": "В наличии",
  "Out of Stock": "Нет в наличии",
  "Digital Instant Delivery": "Мгновенная цифровая доставка",
  "Secure Payment": "Безопасная оплата",
  "Gaming Top-Ups": "Пополнение игр",
  "Gift Cards": "Подарочные карты",
  Subscriptions: "Подписки",
  "Game Keys": "Ключи игр",
  "Product Categories": "Категории товаров",
  "Customer Help": "Помощь клиентам",
  "View All Products": "Все товары",
  "Track Your Order": "Отследить заказ",
  "Order Number": "Номер заказа",
  "Payment status": "Статус платежа",
  "Customer email": "Email клиента",
  "Check Delivery Status": "Проверить статус доставки",
  "Your Digital Product Is Ready": "Ваш цифровой товар готов",
  "Thank You for Your Order": "Спасибо за ваш заказ",
  "Payment is verified. Your private codes are displayed below.": "Платёж подтверждён. Ваши личные коды показаны ниже.",
  "Payment Pending": "Ожидание оплаты",
  "Payment Review": "Проверка платежа",
  "Your order": "Ваш заказ",
  "Order details": "Детали заказа",
  "No orders found.": "Заказы не найдены.",
  "Chat": "Чат",
  "Purchases": "Покупки",
  "Popular": "Популярное",
  "Explore the catalog": "Каталог товаров",
  "All": "Все",
  "All products": "Все товары",
  "View all products": "Смотреть все товары",
  "B2B bulk products": "Оптовые товары B2B",
  "Affiliate program": "Партнёрская программа",
  "Games": "Игры",
  "PlayStation": "PlayStation",
  "Steam": "Steam",
  "Apple & App Store": "Apple и App Store",
  "Legal": "Правовая информация",
  "Your Privacy": "Ваша конфиденциальность",
  "These terms govern access to InGamePin and purchases of gaming top-ups, gift cards, subscriptions and game keys. InGamePin is operated by AMAN G.":
    "Настоящие условия регулируют доступ к InGamePin и покупку игровых пополнений, подарочных карт, подписок и игровых ключей. Сервис InGamePin управляется AMAN G.",
  "This policy explains how InGamePin, operated by AMAN G, collects, uses, shares and protects personal information.":
    "Эта политика объясняет, как InGamePin под управлением AMAN G собирает, использует, передаёт и защищает персональную информацию.",
  "Effective date and acceptance": "Дата вступления в силу и принятие условий",
  "Business identity": "Сведения о компании",
  "Eligibility and account responsibility": "Право на использование и ответственность за аккаунт",
  "Products and regional restrictions": "Товары и региональные ограничения",
  "Orders and customer information": "Заказы и сведения о покупателе",
  "Prices, taxes and payment": "Цены, налоги и оплата",
  "Digital codes and licenses": "Цифровые коды и лицензии",
  "Cancellations, returns and refunds": "Отмена, возврат товаров и средств",
  "Acceptable use": "Допустимое использование",
  "Disclaimers and liability": "Отказ от гарантий и ответственность",
  "Governing law and disputes": "Применимое право и споры",
  "Grievance officer and contact": "Ответственное лицо и контакты",
  "Effective date and who we are": "Дата вступления в силу и сведения о нас",
  "Information we collect": "Какие данные мы собираем",
  "How and why we use information": "Как и зачем мы используем данные",
  "Payments and digital assets": "Платежи и цифровые активы",
  "Cookies and local storage": "Файлы cookie и локальное хранилище",
  "Sharing and service providers": "Передача данных и поставщики услуг",
  "International processing": "Международная обработка данных",
  "Retention": "Хранение данных",
  "Your choices and rights": "Ваш выбор и права",
  "Children": "Дети",
  "Updates and privacy contact": "Обновления и контакты по вопросам конфиденциальности",
  "By accessing InGamePin, creating an account or placing an order, you agree to these Terms & Conditions and the policies linked on this website. If you do not agree, do not use the service.":
    "Получая доступ к InGamePin, создавая аккаунт или размещая заказ, вы соглашаетесь с настоящими Условиями использования и политиками, опубликованными на сайте. Если вы не согласны, не используйте сервис.",
  "References to “InGamePin”, “we”, “us” and “our” mean the InGamePin business operated by AMAN G.":
    "Упоминания «InGamePin», «мы», «нас» и «наш» означают сервис InGamePin, управляемый AMAN G.",
  "You must be legally capable of entering a contract under applicable law. If you are a minor, a parent or legal guardian must make or authorize the purchase.":
    "Вы должны иметь законное право заключать договор согласно применимому законодательству. Если вы несовершеннолетний, покупку должен совершить или разрешить родитель либо законный опекун.",
  "You are responsible for providing accurate order information, safeguarding login credentials and activity performed through your account. Notify us promptly if you suspect unauthorized access.":
    "Вы несёте ответственность за точность данных заказа, сохранность данных для входа и действия, выполненные через ваш аккаунт. Немедленно сообщите нам, если подозреваете несанкционированный доступ.",
  "We sell digital products, including Gaming Top-Ups, Gift Cards, Subscriptions and Game Keys. Product availability, pricing, stock and delivery estimates may change before an order is accepted.":
    "Мы продаём цифровые товары, включая игровые пополнения, подарочные карты, подписки и игровые ключи. Доступность, цена, наличие и срок доставки могут измениться до принятия заказа.",
  "Products may be restricted by country, region, currency, platform, account type, device, publisher rules or activation period. You must review the product description and confirm compatibility before ordering.":
    "Товары могут иметь ограничения по стране, региону, валюте, платформе, типу аккаунта, устройству, правилам издателя или сроку активации. Перед заказом проверьте описание и совместимость товара.",
  "An order is an offer to purchase. We may accept, reject, hold or cancel it for stock issues, pricing or description errors, suspected fraud, sanctions or legal compliance, payment failure, or inability to verify necessary details.":
    "Заказ является предложением о покупке. Мы можем принять, отклонить, приостановить или отменить его из-за отсутствия товара, ошибки в цене или описании, подозрения в мошенничестве, санкций, требований закона, сбоя оплаты или невозможности проверить необходимые сведения.",
  "For player-ID top-ups, you must provide the correct player ID, server, zone and other requested identifiers. A successfully credited top-up cannot normally be reversed or transferred.":
    "Для пополнения по ID игрока необходимо указать правильный ID, сервер, зону и другие запрошенные данные. Успешно зачисленное пополнение обычно нельзя отменить или перенести.",
  "The checkout page shows the product price, applicable payment-gateway fee and final order total in the selected display currency. Settlement may be processed in another supported currency or digital asset by the selected provider.":
    "На странице оформления отображаются цена товара, комиссия платёжного сервиса и итоговая сумма в выбранной валюте. Выбранный провайдер может провести расчёт в другой поддерживаемой валюте или цифровом активе.",
  "Available methods may include InGamePin Wallet, Binance Pay, FreeKassa, Pally, direct USDT networks and other methods displayed at checkout. Provider, network and currency-conversion charges outside the displayed order total are the customer’s responsibility unless stated otherwise.":
    "Доступные способы могут включать кошелёк InGamePin, Binance Pay, FreeKassa, Pally, прямые сети USDT и другие варианты, показанные при оформлении. Если не указано иное, комиссии провайдера, сети и конвертации вне показанной суммы оплачивает покупатель.",
  "An order is paid only after payment is confirmed through our records or the provider’s authenticated notification. Taxes are handled according to the transaction and applicable law.":
    "Заказ считается оплаченным только после подтверждения платежа в наших записях или заверенном уведомлении провайдера. Налоги учитываются в соответствии с операцией и применимым законодательством.",
  "Products may be delivered instantly from available inventory or fulfilled manually after successful payment verification and applicable risk checks. The product page identifies the relevant delivery method and estimate.":
    "Товары могут доставляться мгновенно из доступного запаса или вручную после успешной проверки платежа и рисков. Способ и ориентировочный срок доставки указаны на странице товара.",
  "Delivery may occur on-screen, by email, through the customer account, as a downloadable file, or by direct credit to the submitted player account. Delivery estimates are not guarantees where supplier availability, publisher systems, maintenance, incorrect information or security review causes delay.":
    "Доставка может выполняться на экране, по электронной почте, через аккаунт покупателя, в виде загружаемого файла или прямым зачислением на указанный игровой аккаунт. Сроки не гарантируются, если задержка вызвана доступностью поставщика, системами издателя, техническими работами, неверными данными или проверкой безопасности.",
  "Gift cards, subscription codes and game keys are licensed digital entitlements subject to the issuer’s terms. Associated games, services, brands and intellectual property remain with their respective owners.":
    "Подарочные карты, коды подписок и игровые ключи являются лицензированными цифровыми правами и регулируются условиями эмитента. Игры, сервисы, бренды и интеллектуальная собственность принадлежат соответствующим владельцам.",
  "A code is treated as delivered when made available through the stated delivery channel. Keep codes confidential. We may request redemption-error evidence and issuer or platform details when investigating a claim.":
    "Код считается доставленным после его предоставления через указанный канал. Храните коды в тайне. При рассмотрении претензии мы можем запросить доказательство ошибки активации и сведения об эмитенте или платформе.",
  "Digital orders may be processed immediately. Cancellation is not guaranteed after processing, code disclosure or successful top-up. Eligibility and the claim process are described in our":
    "Цифровые заказы могут обрабатываться немедленно. После обработки, раскрытия кода или успешного пополнения отмена не гарантируется. Условия и порядок подачи претензии описаны в нашей",
  "which forms part of these terms.": "которая является частью настоящих условий.",
  "You must not use InGamePin for fraud, money laundering, unauthorized payments, unlawful resale, service disruption, scraping, malicious code, impersonation, or attempts to bypass security, purchase limits or regional restrictions.":
    "Запрещено использовать InGamePin для мошенничества, отмывания денег, несанкционированных платежей, незаконной перепродажи, нарушения работы сервиса, сбора данных, вредоносного кода, выдачи себя за другое лицо или обхода защиты, лимитов и региональных ограничений.",
  "We may hold orders, restrict access or close accounts where reasonably necessary to protect customers, InGamePin or service providers and to comply with applicable law.":
    "Мы можем приостанавливать заказы, ограничивать доступ или закрывать аккаунты, если это обоснованно необходимо для защиты покупателей, InGamePin или поставщиков услуг и соблюдения закона.",
  "Third-party publisher, platform, payment and network services are outside our control. To the extent permitted by law, InGamePin is not liable for indirect or consequential loss or loss caused by customer-supplied errors, incompatibility or misuse.":
    "Сервисы сторонних издателей, платформ, платёжных систем и сетей находятся вне нашего контроля. В пределах, разрешённых законом, InGamePin не отвечает за косвенные убытки либо ущерб из-за ошибок покупателя, несовместимости или неправильного использования.",
  "Nothing in these terms excludes liability that cannot legally be excluded or limits a non-waivable statutory consumer right.":
    "Настоящие условия не исключают ответственность, которую нельзя исключить по закону, и не ограничивают неотчуждаемые права потребителя.",
  "These terms are governed by the laws of India. Courts having jurisdiction under applicable Indian law may hear disputes. International customers may also retain mandatory consumer rights that apply in their place of residence.":
    "Настоящие условия регулируются законодательством Индии. Споры рассматриваются судами, обладающими юрисдикцией по законодательству Индии. Международные покупатели также сохраняют обязательные права потребителей по месту проживания.",
  "Please contact us before formal proceedings so we can attempt to resolve the matter.":
    "Свяжитесь с нами до начала официального разбирательства, чтобы мы могли попытаться урегулировать вопрос.",
  "Please include your order number and account email when contacting us about a purchase.":
    "При обращении по вопросу покупки укажите номер заказа и адрес электронной почты аккаунта.",
  "InGamePin is operated by AMAN G, GSTIN 19CMAPG4174K1ZV, at Chandpur Leningarh, near Jagorani Sangha Club, South Jogendra Nagar, Kolkata, West Bengal 700110, India. Privacy requests may be sent to":
    "Сервис InGamePin управляется AMAN G, GSTIN 19CMAPG4174K1ZV, по адресу: Chandpur Leningarh, near Jagorani Sangha Club, South Jogendra Nagar, Kolkata, West Bengal 700110, India. Запросы по вопросам конфиденциальности можно направлять на",
  "Identity and contact information supplied by you, such as name, email address, phone number, address and tax identification details.": "Предоставленные вами идентификационные и контактные данные: имя, электронная почта, телефон, адрес и налоговые сведения.",
  "Account, authentication, security-setting and customer-preference information.": "Данные аккаунта, аутентификации, настроек безопасности и предпочтений покупателя.",
  "Order data, including products, player ID, server or zone, platform, region, delivery status and delivered-content records.": "Данные заказа, включая товары, ID игрока, сервер или зону, платформу, регион, статус доставки и записи о доставленном содержимом.",
  "Payment and verification data, including method, amount, provider references, transaction identifiers and wallet activity. We do not ask for private wallet keys or full payment credentials.": "Данные платежа и проверки: способ, сумма, ссылки провайдера, идентификаторы транзакций и операции кошелька. Мы не запрашиваем закрытые ключи кошелька или полные платёжные реквизиты.",
  "Affiliate applications, referrals, commissions, payout addresses and related fraud-prevention information.": "Партнёрские заявки, рефералы, комиссии, адреса выплат и связанные данные для предотвращения мошенничества.",
  "Support and live-chat communications, complaints, screenshots and investigation records.": "Обращения в поддержку и онлайн-чат, жалобы, снимки экрана и материалы расследований.",
  "Device, browser, IP address, approximate location, referral, cookie and website-usage information.": "Данные об устройстве, браузере, IP-адресе, примерном местоположении, источнике перехода, cookie и использовании сайта.",
  "We use information to provide accounts; accept, verify and deliver orders; complete top-ups; manage wallet and affiliate services; prevent fraud and abuse; communicate order, delivery, security and policy updates; provide support; issue invoices; maintain the website; comply with accounting, tax and legal duties; and establish or defend legal claims.": "Мы используем данные для работы аккаунтов; принятия, проверки и доставки заказов; выполнения пополнений; управления кошельком и партнёрской программой; предотвращения мошенничества; отправки уведомлений; поддержки; выставления счетов; обслуживания сайта; выполнения бухгалтерских, налоговых и юридических обязанностей; а также защиты правовых требований.",
  "Depending on applicable law, processing is based on performance of a contract, legal obligations, legitimate interests such as security and service improvement, or consent.": "В зависимости от применимого права обработка основана на исполнении договора, юридических обязанностях, законных интересах, таких как безопасность и улучшение сервиса, либо согласии.",
  "Payment transactions may be processed by Binance Pay, FreeKassa, Pally, blockchain networks or other providers shown at checkout. These providers handle information under their own terms. We receive the status and identifiers needed to verify and reconcile a transaction.": "Платежи могут обрабатываться Binance Pay, FreeKassa, Pally, блокчейн-сетями или другими провайдерами, указанными при оформлении. Они обрабатывают данные по собственным условиям. Мы получаем статус и идентификаторы, необходимые для проверки операции.",
  "Wallet records include credits, debits, refunds and related order history. Public blockchain transactions may remain visible permanently on the applicable network.": "Записи кошелька включают зачисления, списания, возвраты и связанную историю заказов. Публичные блокчейн-транзакции могут навсегда оставаться видимыми в соответствующей сети.",
  "We use essential cookies and local storage for sessions, authentication, carts, preferences, affiliate attribution, security and checkout. Analytics or performance technologies may be used to improve reliability.": "Мы используем необходимые cookie и локальное хранилище для сессий, аутентификации, корзины, настроек, партнёрской атрибуции, безопасности и оформления заказа. Для повышения надёжности могут применяться аналитические технологии.",
  "Blocking essential storage may prevent account, cart or checkout functions from working. Where required, consent will be requested before non-essential technologies are used.": "Блокировка необходимого хранилища может нарушить работу аккаунта, корзины или оформления заказа. Когда это требуется, перед использованием необязательных технологий запрашивается согласие.",
  "We share only information reasonably necessary with hosting, database, authentication, email, analytics, fraud-prevention, customer-support, payment, blockchain-monitoring, supplier, distributor, publisher and delivery providers. A player ID may be supplied to a fulfillment provider to complete a top-up.": "Мы передаём только разумно необходимые данные поставщикам хостинга, баз данных, аутентификации, электронной почты, аналитики, защиты от мошенничества, поддержки, платежей, блокчейн-мониторинга, поставок и доставки. ID игрока может быть передан исполнителю для пополнения.",
  "We may disclose information when required by law, to protect rights and security, during a business reorganization, or at your direction. We do not sell personal information for money.": "Мы можем раскрывать данные по требованию закона, для защиты прав и безопасности, при реорганизации бизнеса или по вашему указанию. Мы не продаём персональные данные за деньги.",
  "InGamePin serves customers internationally. Providers, publishers and suppliers may process information outside your country. Where required, we use appropriate contractual or legal safeguards, although other countries may have different data-protection laws.": "InGamePin обслуживает покупателей по всему миру. Провайдеры, издатели и поставщики могут обрабатывать данные за пределами вашей страны. При необходимости мы применяем договорные или юридические гарантии, хотя законы о защите данных в других странах могут отличаться.",
  "We retain information only as long as reasonably necessary for orders, delivery, support, fraud prevention, disputes, and legal, tax or accounting obligations. Retention varies by record type. Data is then deleted, anonymized or securely isolated unless continued retention is required.": "Мы храним данные только столько, сколько разумно необходимо для заказов, доставки, поддержки, предотвращения мошенничества, споров и юридических, налоговых или бухгалтерских обязанностей. Затем данные удаляются, обезличиваются или безопасно изолируются, если дальнейшее хранение не требуется.",
  "Blockchain records and records held independently by payment providers may not be erasable by InGamePin.": "InGamePin может не иметь возможности удалить записи блокчейна и данные, независимо хранящиеся платёжными провайдерами.",
  "We use reasonable administrative, technical and organizational safeguards, including access controls, encrypted connections, multi-factor authentication options and vetted service providers. No online system is completely secure. Protect your password, passkeys and authenticator codes and report suspected unauthorized access promptly.": "Мы применяем разумные административные, технические и организационные меры защиты, включая контроль доступа, шифрование, многофакторную аутентификацию и проверенных поставщиков. Ни одна онлайн-система не защищена полностью. Берегите пароль, ключи доступа и коды аутентификатора и немедленно сообщайте о подозрительном доступе.",
  "Subject to applicable law, you may request access, correction, deletion, withdrawal of consent, or information about how your personal data is handled. We may verify identity before acting.": "В соответствии с применимым законом вы можете запросить доступ, исправление, удаление, отзыв согласия или сведения об обработке персональных данных. Перед выполнением запроса мы можем проверить вашу личность.",
  "Information required for an active transaction, fraud prevention, accounting, tax, disputes or legal compliance may be retained where legally permitted or required.": "Данные, необходимые для активной операции, предотвращения мошенничества, бухгалтерского или налогового учёта, споров или соблюдения закона, могут храниться, если это разрешено или требуется законом.",
  "InGamePin is not intended for children who cannot legally consent to data processing or enter a contract. A parent or guardian should supervise purchases by minors. Contact us if you believe a child supplied information without proper authorization.": "InGamePin не предназначен для детей, которые не могут законно согласиться на обработку данных или заключить договор. Покупки несовершеннолетних должен контролировать родитель или опекун. Свяжитесь с нами, если ребёнок предоставил данные без надлежащего разрешения.",
  "We may update this policy prospectively to reflect legal, service or operational changes. The effective date above will be updated when material changes are published.": "Мы можем обновлять эту политику с учётом правовых, сервисных или операционных изменений. При публикации существенных изменений дата вступления в силу будет обновлена.",
  "Customer Policy": "Политика для покупателей",
  "This policy explains cancellations, replacements and refunds for digital products purchased from InGamePin, operated by AMAN G.": "Эта политика объясняет порядок отмены, замены и возврата средств за цифровые товары, приобретённые в InGamePin под управлением AMAN G.",
  "Effective date": "Дата вступления в силу",
  "Digital-product policy": "Политика в отношении цифровых товаров",
  "When a remedy may be available": "Когда возможно возмещение",
  "Generally non-refundable cases": "Случаи, обычно не подлежащие возврату",
  "Cancellation": "Отмена",
  "How to make a claim": "Как подать претензию",
  "Investigation and processing": "Проверка и обработка",
  "Payment failures and disputes": "Сбои платежей и споры",
  "Contact and grievance officer": "Контакты и ответственное лицо",
  "Gaming Top-Ups, Gift Cards, Subscriptions and Game Keys are digital products that cannot be physically returned. Once a valid code is revealed, downloaded or delivered, or a top-up or subscription is successfully applied, the order is normally final.": "Игровые пополнения, подарочные карты, подписки и игровые ключи являются цифровыми товарами, которые нельзя вернуть физически. После раскрытия, загрузки или доставки действительного кода либо успешного применения пополнения или подписки заказ обычно считается окончательным.",
  "This policy does not limit a refund, replacement or other remedy required by applicable consumer law.": "Настоящая политика не ограничивает возврат средств, замену или иное возмещение, предусмотренное применимым законодательством о защите потребителей.",
  "Contact us if a paid product was not delivered within its stated or a reasonable delivery time; a delivered code was already redeemed before delivery or is confirmed invalid; the wrong product was delivered because of our error; a top-up failed and was not credited; or you were charged more than once for the same order.": "Свяжитесь с нами, если оплаченный товар не доставлен в указанный или разумный срок; доставленный код был активирован до доставки или признан недействительным; по нашей ошибке доставлен неверный товар; пополнение не выполнено и не зачислено; либо с вас несколько раз списали средства за один заказ.",
  "After verification, the remedy may be re-delivery, replacement, InGamePin Wallet credit or refund to the original payment method, depending on the circumstances and applicable law.": "После проверки возможны повторная доставка, замена, зачисление на кошелёк InGamePin или возврат на первоначальный способ оплаты — в зависимости от обстоятельств и применимого закона.",
  "A valid code has been viewed, copied, downloaded, shared, redeemed or resold.": "Действительный код был просмотрен, скопирован, загружен, передан, активирован или перепродан.",
  "A top-up was successfully credited to the player ID, server or zone supplied by the customer.": "Пополнение успешно зачислено на ID игрока, сервер или зону, указанные покупателем.",
  "The customer selected an incompatible country, region, platform, currency, edition, denomination or account.": "Покупатель выбрал несовместимую страну, регион, платформу, валюту, издание, номинал или аккаунт.",
  "The correctly delivered product is no longer wanted.": "Правильно доставленный товар больше не нужен покупателю.",
  "The customer’s account is restricted by a publisher or platform.": "Аккаунт покупателя ограничен издателем или платформой.",
  "Payment cannot be verified as received by InGamePin.": "Получение платежа сервисом InGamePin невозможно подтвердить.",
  "A blockchain transfer was sent using the wrong network, token or address.": "Блокчейн-перевод отправлен через неверную сеть, с неверным токеном или адресом.",
  "We will still provide a remedy where applicable law requires one.": "Мы предоставим возмещение, если этого требует применимое законодательство.",
  "Request cancellation immediately. We may cancel an order only while it remains unprocessed and no code, entitlement or top-up has been supplied. Automatic fulfillment or manual preparation may begin promptly, so a request does not guarantee cancellation.": "Запрашивайте отмену немедленно. Мы можем отменить заказ только до начала обработки и до предоставления кода, цифрового права или пополнения. Автоматическое выполнение или ручная подготовка могут начаться сразу, поэтому запрос не гарантирует отмену.",
  "For code issues, keep the code confidential and provide the platform’s redemption error and, if requested, evidence from the issuer showing activation or redemption status. For player-ID top-ups, provide the submitted ID and server plus relevant account evidence.": "При проблеме с кодом сохраняйте его конфиденциальность и предоставьте ошибку активации платформы, а по запросу — подтверждение эмитента о статусе активации. Для пополнения по ID игрока сообщите указанный ID, сервер и соответствующие сведения аккаунта.",
  "We may verify payment, delivery logs, download records, code status, player-account credit and supplier or publisher records. Additional information may be requested where reasonably necessary to prevent fraud and determine the claim.": "Мы можем проверять платёж, журналы доставки, записи загрузки, статус кода, зачисление на игровой аккаунт и данные поставщика или издателя. Для предотвращения мошенничества и рассмотрения претензии могут быть запрошены дополнительные сведения.",
  "Approved refunds are sent to the original payment method where practical. Cryptocurrency refunds may require verification of the refund address and network and may be reduced only by unavoidable provider or network costs where permitted and clearly disclosed. Provider and blockchain processing times are outside our control.": "Одобренный возврат по возможности направляется на первоначальный способ оплаты. Для возврата криптовалюты может потребоваться проверка адреса и сети; сумма может быть уменьшена только на неизбежные комиссии провайдера или сети, если это разрешено и ясно указано. Сроки обработки провайдером и блокчейном находятся вне нашего контроля.",
  "If funds were debited but InGamePin did not receive them, allow the provider’s normal reversal period and contact us with the transaction reference. Do not make a duplicate payment unless instructed.": "Если средства списаны, но InGamePin их не получил, дождитесь стандартного срока отмены операции провайдером и свяжитесь с нами, указав идентификатор транзакции. Не совершайте повторный платёж без инструкции.",
  "Please contact us before opening a payment dispute so we can investigate. Fraudulent chargebacks, false invalid-code claims or altered evidence may result in account restriction and lawful recovery action.": "Перед открытием платёжного спора свяжитесь с нами для проведения проверки. Мошеннические возвратные платежи, ложные заявления о недействительном коде или изменённые доказательства могут привести к ограничению аккаунта и законным мерам взыскания.",
  "InGamePin Marketing Partners": "Маркетинговые партнёры InGamePin",
  "Join the InGamePin Affiliate Program, create referral links for eligible products and earn commission from completed, approved customer orders.": "Присоединяйтесь к партнёрской программе InGamePin, создавайте реферальные ссылки на подходящие товары и получайте комиссию с завершённых и одобренных заказов.",
  "Read Program Terms": "Читать условия программы",
  "Applications are currently closed": "Приём заявок временно закрыт",
  "Referral tracking": "Срок отслеживания",
  "Commission holding": "Удержание комиссии",
  "Minimum payout": "Минимальная выплата",
  "Payout fee": "Комиссия за выплату",
  "days": "дней",
  "How it works": "Как это работает",
  "Sign in, submit your promotion details and wait for administrator approval.": "Войдите, укажите сведения о продвижении и дождитесь одобрения администратора.",
  "Choose an eligible product, set an allowed commission and copy your referral link.": "Выберите подходящий товар, установите разрешённую комиссию и скопируйте реферальную ссылку.",
  "Share accurate product information through your approved marketing channels.": "Распространяйте точную информацию о товарах через одобренные маркетинговые каналы.",
  "Approved commission becomes available after the holding period and can be withdrawn.": "Одобренная комиссия становится доступной после срока удержания и может быть выведена.",
  "Legal agreement": "Юридическое соглашение",
  "Last updated: August 12, 2026": "Последнее обновление: 12 августа 2026 г.",
  "InGamePin Affiliate Program Terms & Conditions": "Условия партнёрской программы InGamePin",
  "1. Agreement and operator": "1. Соглашение и оператор",
  "2. Eligibility and approval": "2. Право на участие и одобрение",
  "3. Referral links and tracking": "3. Реферальные ссылки и отслеживание",
  "4. Product pricing and commission": "4. Цена товара и комиссия",
  "5. Valid commission": "5. Действительная комиссия",
  "6. Self-referrals and prohibited activity": "6. Саморефералы и запрещённые действия",
  "7. Promotion standards": "7. Стандарты продвижения",
  "8. Holding period and available balance": "8. Срок удержания и доступный баланс",
  "9. USDT payouts": "9. Выплаты USDT",
  "10. Taxes and legal responsibility": "10. Налоги и юридическая ответственность",
  "11. Suspension and termination": "11. Приостановление и прекращение",
  "12. Program changes and contact": "12. Изменения программы и контакты",
  "The InGamePin Affiliate Program is operated by AMAN G. By applying, participating, creating an affiliate link or requesting a payout, you agree to these Terms & Conditions and all applicable laws.": "Партнёрская программа InGamePin управляется AMAN G. Подавая заявку, участвуя, создавая партнёрскую ссылку или запрашивая выплату, вы соглашаетесь с настоящими условиями и применимыми законами.",
  "You must provide complete and accurate application information and use only one affiliate account unless written permission is given. Applications may be approved, rejected, suspended or reviewed at InGamePin's discretion. Approval does not create employment, agency, franchise or partnership.": "Вы должны предоставить полные и точные сведения и использовать только один партнёрский аккаунт, если письменное разрешение не предусматривает иное. InGamePin может одобрить, отклонить, приостановить или пересмотреть заявку. Одобрение не создаёт трудовых, агентских, франчайзинговых или партнёрских отношений.",
  "You must provide complete and accurate application information and use only one affiliate account unless written permission is given. Applications may be approved, rejected, suspended or reviewed at InGamePin’s discretion. Approval does not create employment, agency, franchise or partnership.": "Вы должны предоставить полные и точные сведения и использовать только один партнёрский аккаунт, если письменное разрешение не предусматривает иное. InGamePin может одобрить, отклонить, приостановить или пересмотреть заявку. Одобрение не создаёт трудовых, агентских, франчайзинговых или партнёрских отношений.",
  "You may select a commission rate only within the limit configured for each eligible product. The selected affiliate commission is added to the product price and the customer sees the final price before payment. Commission is calculated from the rate recorded when the order is created. Rates, eligible products and limits may change.": "Вы можете выбрать ставку комиссии только в пределах лимита, установленного для подходящего товара. Партнёрская комиссия добавляется к цене товара, и покупатель видит итоговую цену до оплаты. Комиссия рассчитывается по ставке на момент создания заказа. Ставки, товары и лимиты могут изменяться.",
  "Commission is earned only on successfully paid, verified and fulfilled orders. No commission is payable for cancelled, refunded, charged-back, duplicated, fraudulent or otherwise invalid orders. Commission may be reversed or withheld when an order later becomes ineligible.": "Комиссия начисляется только за успешно оплаченные, проверенные и выполненные заказы. Комиссия не выплачивается за отменённые, возвращённые, оспоренные, дублированные, мошеннические или иные недействительные заказы. Комиссия может быть отменена или удержана, если заказ позднее станет неподходящим.",
  "Purchasing through your own referral link does not earn commission. You must not use fake accounts, bots, cookie stuffing, forced redirects, misleading claims, unsolicited spam, stolen payment methods, trademark impersonation, artificial orders or any method intended to manipulate attribution, prices, clicks or commission.": "Покупка по собственной реферальной ссылке не приносит комиссию. Запрещено использовать поддельные аккаунты, ботов, cookie stuffing, принудительные перенаправления, вводящие в заблуждение заявления, спам, украденные способы оплаты, имитацию товарных знаков, искусственные заказы и любые методы манипуляции атрибуцией, ценами, кликами или комиссией.",
  "Promotions must be lawful, accurate and clearly identify your affiliate relationship. Do not claim to be InGamePin, guarantee unavailable prices or delivery times, copy official accounts, or use InGamePin branding in a domain or social username without written permission. You are responsible for content posted through your channels.": "Продвижение должно быть законным, точным и ясно раскрывать партнёрские отношения. Нельзя выдавать себя за InGamePin, гарантировать недоступные цены или сроки, копировать официальные аккаунты либо использовать бренд InGamePin в домене или имени социальной сети без письменного разрешения. Вы отвечаете за содержимое своих каналов.",
  "You are responsible for reporting and paying taxes, duties and other obligations arising from affiliate income in your country. You must have the legal capacity and permissions required to participate.": "Вы отвечаете за декларирование и уплату налогов, пошлин и иных обязательств с партнёрского дохода в своей стране и должны обладать необходимой правоспособностью и разрешениями.",
  "InGamePin may suspend or terminate an affiliate account, cancel invalid commission, delay a payout for investigation or request additional verification where fraud, abuse, policy violations, chargebacks or legal risks are suspected. Confirmed valid available commission remains subject to these terms.": "InGamePin может приостановить или закрыть партнёрский аккаунт, отменить недействительную комиссию, задержать выплату для проверки или запросить дополнительное подтверждение при подозрении на мошенничество, злоупотребление, нарушение правил, возврат платежа или юридические риски. Подтверждённая доступная комиссия по-прежнему регулируется этими условиями.",
  "InGamePin may update the program, rates, products, payout rules or these terms. Continued participation after an update means you accept the revised terms. Questions may be sent to": "InGamePin может изменять программу, ставки, товары, правила выплат или настоящие условия. Продолжение участия после обновления означает принятие новых условий. Вопросы можно направлять по адресу",
  "Your application will be reviewed before referral tools are enabled.": "Ваша заявка будет проверена до активации реферальных инструментов.",
};

Object.assign(russianText, {
  "Marketing partners": "Маркетинговые партнёры",
  "Apply to promote InGamePin products and earn commission from approved sales.":
    "Подайте заявку на продвижение товаров InGamePin и получайте комиссию с одобренных продаж.",
  "Tell us where and how you plan to promote InGamePin.":
    "Расскажите, где и как вы планируете продвигать InGamePin.",
  "Main promotion channel": "Основной канал продвижения",
  "Promotion page URL": "Ссылка на страницу продвижения",
  "Promotion plan": "План продвижения",
  "Website or blog": "Сайт или блог",
  "Social media": "Социальные сети",
  Other: "Другое",
  "Explain how and where you will promote InGamePin products.":
    "Объясните, как и где вы будете продвигать товары InGamePin.",
  "I have read and agree to the": "Я прочитал(а) и принимаю",
  "Affiliate Program Terms & Conditions":
    "условия партнёрской программы",
  "Submit Application": "Отправить заявку",
  "Full name": "Полное имя",
  Country: "Страна",
  "Promotion channel": "Канал продвижения",
  "Product default rate": "Стандартная ставка товара",
  "Link clicks": "Переходы по ссылкам",
  "Approved sales": "Одобренные продажи",
  "Pending commission": "Ожидающая комиссия",
  "Promote products": "Продвигать товары",
  "Copy a product link and share it with your audience.":
    "Скопируйте ссылку на товар и поделитесь ею со своей аудиторией.",
  "Request payout": "Запросить выплату",
  "Payouts are reviewed and sent manually by the administrator.":
    "Выплаты проверяются и отправляются администратором вручную.",
  Available: "Доступно",
  "Fixed fee": "Фиксированная комиссия",
  "You receive": "Вы получите",
  "USDT network": "Сеть USDT",
  "USDT wallet address": "Адрес USDT-кошелька",
  "Enter the address for the selected network":
    "Введите адрес для выбранной сети",
  "Payout history": "История выплат",
  PENDING: "ОЖИДАЕТ",
  APPROVED: "ОДОБРЕНО",
  REJECTED: "ОТКЛОНЕНО",
  SUSPENDED: "ПРИОСТАНОВЛЕНО",
});

const thaiText: Record<string, string> = {
  "Digital Delivery": "การจัดส่งดิจิทัล",
  "Return to dashboard": "กลับไปที่แดชบอร์ด",
  "← Return to dashboard": "← กลับไปที่แดชบอร์ด",
  "Available balance": "ยอดเงินที่ใช้ได้",
  "USD wallet": "กระเป๋าเงิน USD",
  "Add money": "เติมเงิน",
  "Choose an amount and pay using any available gateway.":
    "เลือกจำนวนเงินและชำระผ่านช่องทางที่พร้อมใช้งาน",
  "Add money through any available payment gateway.":
    "เติมเงินผ่านช่องทางการชำระเงินที่พร้อมใช้งาน",
  "Your balance is credited automatically after verified payment.":
    "ยอดเงินจะเข้ากระเป๋าโดยอัตโนมัติหลังยืนยันการชำระเงิน",
  "Top-up amount (USD)": "จำนวนเงินเติม (USD)",
  "Payment method": "วิธีชำระเงิน",
  "Instant verification": "ยืนยันทันที",
  "Cards and local methods": "บัตรและช่องทางท้องถิ่น",
  "Available payment methods": "วิธีชำระเงินที่พร้อมใช้งาน",
  "Add amount": "จำนวนเงินเติม",
  "New balance": "ยอดเงินใหม่",
  "Continue to payment": "ดำเนินการชำระเงิน",
  "Bulk delivery information": "ข้อมูลการจัดส่งแบบขายส่ง",
  "Bulk Delivery Time: 1-15 Working Days": "ระยะเวลาจัดส่งแบบขายส่ง: 1–15 วันทำการ",
  "Please confirm that you understand the delivery time.":
    "โปรดยืนยันว่าคุณเข้าใจระยะเวลาจัดส่ง",
  "I understand": "ฉันเข้าใจ",
  Cancel: "ยกเลิก",
  "Opening payment gateway...": "กำลังเปิดช่องทางชำระเงิน...",
  "Recent top-ups": "รายการเติมเงินล่าสุด",
  "No top-ups yet.": "ยังไม่มีรายการเติมเงิน",
  "Welcome back": "ยินดีต้อนรับกลับ",
  "Sign in to manage your orders, wallet and profile.":
    "เข้าสู่ระบบเพื่อจัดการคำสั่งซื้อ กระเป๋าเงิน และโปรไฟล์",
  "Customer account": "บัญชีลูกค้า",
  "Email address": "อีเมล",
  Password: "รหัสผ่าน",
  "Sign in": "เข้าสู่ระบบ",
  "Forgot password?": "ลืมรหัสผ่าน?",
  "New customer?": "ลูกค้าใหม่?",
  "Create account": "สร้างบัญชี",
  "Create your account": "สร้างบัญชีของคุณ",
  "Already have an account?": "มีบัญชีอยู่แล้ว?",
  "Enter your OTP": "กรอกรหัส OTP",
  "Verify & Activate Account": "ยืนยันและเปิดใช้งานบัญชี",
  "Resend verification code": "ส่งรหัสยืนยันอีกครั้ง",
  "Use a different email address": "ใช้อีเมลอื่น",
  "My orders": "คำสั่งซื้อของฉัน",
  "My codes": "โค้ดของฉัน",
  "My wallet": "กระเป๋าเงินของฉัน",
  Profile: "โปรไฟล์",
  "Sign out": "ออกจากระบบ",
  "Wallet balance": "ยอดเงินในกระเป๋า",
  "Delivered codes": "โค้ดที่จัดส่งแล้ว",
  Notifications: "การแจ้งเตือน",
  "Account details": "รายละเอียดบัญชี",
  "Full name": "ชื่อ-นามสกุล",
  Phone: "โทรศัพท์",
  "Save profile": "บันทึกโปรไฟล์",
  "Shopping Cart": "ตะกร้าสินค้า",
  "Your cart is empty.": "ตะกร้าของคุณว่างเปล่า",
  "Continue shopping": "เลือกซื้อสินค้าต่อ",
  Product: "สินค้า",
  Price: "ราคา",
  Quantity: "จำนวน",
  Subtotal: "ยอดรวมย่อย",
  Discount: "ส่วนลด",
  Delivery: "การจัดส่ง",
  Taxes: "ภาษี",
  "Total Amount": "ยอดรวมทั้งหมด",
  Remove: "ลบ",
  Checkout: "ชำระเงิน",
  "Contact Information": "ข้อมูลติดต่อ",
  "Used for order updates and delivery communication.":
    "ใช้สำหรับแจ้งสถานะคำสั่งซื้อและการจัดส่ง",
  "Order Summary": "สรุปคำสั่งซื้อ",
  "Payment gateway fee": "ค่าธรรมเนียมช่องทางชำระเงิน",
  "Continue to Payment": "ดำเนินการชำระเงิน",
  "Secure checkout": "ชำระเงินอย่างปลอดภัย",
  "Choose your product option": "เลือกตัวเลือกสินค้า",
  "Select product option": "เลือกตัวเลือกสินค้า",
  "Selected option": "ตัวเลือกที่เลือก",
  "Delivery email": "อีเมลสำหรับจัดส่ง",
  "Add to Cart": "เพิ่มลงตะกร้า",
  "Buy Now": "ซื้อเลย",
  "In Stock": "มีสินค้า",
  "Out of Stock": "สินค้าหมด",
  "Digital Instant Delivery": "จัดส่งดิจิทัลทันที",
  "Genuine Products": "สินค้าของแท้",
  "Secure Payment": "ชำระเงินปลอดภัย",
  "Customer Support": "ฝ่ายบริการลูกค้า",
  Home: "หน้าหลัก",
  "All Products": "สินค้าทั้งหมด",
  "Track Order": "ติดตามคำสั่งซื้อ",
  Cart: "ตะกร้า",
  "My Account": "บัญชีของฉัน",
  Login: "เข้าสู่ระบบ",
  Search: "ค้นหา",
  "Gaming Top-Ups": "เติมเงินเกม",
  "Gift Cards": "บัตรของขวัญ",
  Subscriptions: "การสมัครสมาชิก",
  "Game Keys": "คีย์เกม",
  "Product Categories": "หมวดหมู่สินค้า",
  "Customer Help": "ช่วยเหลือลูกค้า",
  "Terms & Conditions": "ข้อกำหนดและเงื่อนไข",
  "Return & Refund Policy": "นโยบายคืนสินค้าและคืนเงิน",
  "Privacy Policy": "นโยบายความเป็นส่วนตัว",
  "Affiliate Program": "โปรแกรมพันธมิตร",
  "View All Products": "ดูสินค้าทั้งหมด",
  "Track Your Order": "ติดตามคำสั่งซื้อของคุณ",
  "Contact Support": "ติดต่อฝ่ายช่วยเหลือ",
  "Order number": "หมายเลขคำสั่งซื้อ",
  "Order Number": "หมายเลขคำสั่งซื้อ",
  "Order status": "สถานะคำสั่งซื้อ",
  "Payment status": "สถานะการชำระเงิน",
  "Customer email": "อีเมลลูกค้า",
  "Check Delivery Status": "ตรวจสอบสถานะการจัดส่ง",
  "Download All Codes (.txt)": "ดาวน์โหลดโค้ดทั้งหมด (.txt)",
  "Download Product Codes": "ดาวน์โหลดโค้ดสินค้า",
  "Secure digital delivery": "การจัดส่งดิจิทัลที่ปลอดภัย",
  "Your Digital Product Is Ready": "สินค้าดิจิทัลของคุณพร้อมแล้ว",
  "Thank You for Your Order": "ขอบคุณสำหรับคำสั่งซื้อ",
  "Payment is verified. Your private codes are displayed below.":
    "ยืนยันการชำระเงินแล้ว โค้ดส่วนตัวของคุณแสดงอยู่ด้านล่าง",
  "Payment Pending": "รอการชำระเงิน",
  "Payment Review": "กำลังตรวจสอบการชำระเงิน",
  "Your order": "คำสั่งซื้อของคุณ",
  "Order details": "รายละเอียดคำสั่งซื้อ",
  "No orders found.": "ไม่พบคำสั่งซื้อ",
  "No delivered digital codes yet.": "ยังไม่มีโค้ดดิจิทัลที่จัดส่งแล้ว",
  "Copy": "คัดลอก",
  "Copied": "คัดลอกแล้ว",
  "Live Chat": "แชตสด",
  "Open live support chat": "เปิดแชตฝ่ายช่วยเหลือ",
  "Mobile number": "หมายเลขโทรศัพท์",
  "Country calling code": "รหัสโทรศัพท์ประเทศ",
  "Loading payment...": "กำลังโหลดการชำระเงิน...",
  "Digital product": "สินค้าดิจิทัล",
  "PENDING PAYMENT": "รอการชำระเงิน",
  "PAYMENT REVIEW": "กำลังตรวจสอบการชำระเงิน",
  PENDING: "รอดำเนินการ",
  PENDING_PAYMENT: "รอการชำระเงิน",
  PAYMENT_REVIEW: "กำลังตรวจสอบการชำระเงิน",
  SUBMITTED: "ส่งแล้ว",
  PAID: "ชำระแล้ว",
  VERIFIED: "ยืนยันแล้ว",
  PROCESSING: "กำลังดำเนินการ",
  DELIVERED: "จัดส่งแล้ว",
  COMPLETED: "เสร็จสมบูรณ์",
  FAILED: "ล้มเหลว",
  CANCELLED: "ยกเลิกแล้ว",
  REJECTED: "ถูกปฏิเสธ",
  REFUNDED: "คืนเงินแล้ว",
  EXPIRED: "หมดอายุ",
  "Minimum amount: $10": "จำนวนขั้นต่ำ: $10",
  "Minimum wallet top-up: $10. New configured gateway adapters appear here automatically.": "เติมเงินขั้นต่ำ $10 ช่องทางชำระเงินใหม่ที่ตั้งค่าแล้วจะแสดงที่นี่โดยอัตโนมัติ",
  "Your cart contains a bulk delivery product. Confirm before continuing to payment.": "ตะกร้าของคุณมีสินค้าจัดส่งแบบขายส่ง โปรดยืนยันก่อนดำเนินการชำระเงิน",
  "Clear cart": "ล้างตะกร้า",
  "Proceed to checkout": "ดำเนินการชำระเงิน",
  "Secure order processing": "ประมวลผลคำสั่งซื้ออย่างปลอดภัย",
  "Complete your details and choose a payment method.": "กรอกข้อมูลและเลือกวิธีชำระเงิน",
  "Billing details": "ข้อมูลเรียกเก็บเงิน",
  "Customer name": "ชื่อลูกค้า",
  "Email for delivery": "อีเมลสำหรับจัดส่ง",
  "Phone number": "หมายเลขโทรศัพท์",
  "Delivery Method": "วิธีจัดส่ง",
  "Payment Method": "วิธีชำระเงิน",
  "Order Note": "หมายเหตุคำสั่งซื้อ",
  "Optional delivery instructions.": "คำแนะนำการจัดส่งเพิ่มเติม (ไม่บังคับ)",
  "Your information is securely processed": "ข้อมูลของคุณได้รับการประมวลผลอย่างปลอดภัย",
  "I agree to the Terms, privacy policy and applicable returns or replacement policy.": "ฉันยอมรับข้อกำหนด นโยบายความเป็นส่วนตัว และนโยบายคืนหรือเปลี่ยนสินค้าที่เกี่ยวข้อง",
  "Payment unavailable": "ไม่สามารถชำระเงินได้",
  "Return to checkout": "กลับไปหน้าชำระเงิน",
  "Order total": "ยอดรวมคำสั่งซื้อ",
  "Pay securely with PayPalych": "ชำระอย่างปลอดภัยด้วย PayPalych",
  "Continue to PayPalych": "ดำเนินการต่อไปยัง PayPalych",
  "Pay with USDT": "ชำระด้วย USDT",
  "Direct wallet payment": "ชำระจากกระเป๋าเงินโดยตรง",
  "Your payment is verified automatically on the blockchain.": "การชำระเงินของคุณจะได้รับการยืนยันอัตโนมัติบนบล็อกเชน",
  "Select the network you will send from": "เลือกเครือข่ายที่คุณจะใช้ส่ง",
  "Solana network": "เครือข่าย Solana",
  Network: "เครือข่าย",
  "Send exactly": "ส่งจำนวนที่ระบุ",
  "Receiving address": "ที่อยู่รับเงิน",
  "Copy address": "คัดลอกที่อยู่",
  "I have sent the payment": "ฉันส่งการชำระเงินแล้ว",
  "Invoice expires in": "ใบแจ้งชำระหมดอายุใน",
  "Payment detected": "ตรวจพบการชำระเงิน",
  "Waiting for blockchain confirmation...": "กำลังรอการยืนยันจากบล็อกเชน...",
  "How can we help?": "เราช่วยคุณได้อย่างไร?",
  "Get help with orders, payments, delivery and your account.": "รับความช่วยเหลือเกี่ยวกับคำสั่งซื้อ การชำระเงิน การจัดส่ง และบัญชีของคุณ",
  "Telegram Support": "ช่วยเหลือผ่าน Telegram",
  "Message us on Telegram": "ส่งข้อความหาเราทาง Telegram",
  "WhatsApp Support": "ช่วยเหลือผ่าน WhatsApp",
  "Message us on WhatsApp": "ส่งข้อความหาเราทาง WhatsApp",
  "Support hours": "เวลาทำการฝ่ายช่วยเหลือ",
  "Frequently asked questions": "คำถามที่พบบ่อย",
  "Track your order": "ติดตามคำสั่งซื้อ",
  "Enter your order number and email address to check its status.": "กรอกหมายเลขคำสั่งซื้อและอีเมลเพื่อตรวจสอบสถานะ",
  "Check status": "ตรวจสอบสถานะ",
  Status: "สถานะ",
  Date: "วันที่",
  Amount: "จำนวนเงิน",
  "Order items": "รายการสินค้า",
  "Featured Products": "สินค้าแนะนำ",
  "Popular Categories": "หมวดหมู่ยอดนิยม",
  "For resellers & businesses": "สำหรับผู้ค้าปลีกและธุรกิจ",
  "Need products in bulk quantity?": "ต้องการสินค้าจำนวนมาก?",
  "Explore bulk products with flexible quantities, competitive B2B pricing and dedicated support.": "เลือกซื้อสินค้าขายส่งด้วยจำนวนที่ยืดหยุ่น ราคา B2B ที่แข่งขันได้ และบริการช่วยเหลือเฉพาะ",
  "View B2B Bulk Products": "ดูสินค้าขายส่ง B2B",
  "B2B Bulk Products": "สินค้าขายส่ง B2B",
  "B2B Bulk": "ขายส่ง B2B",
  "Bulk digital products for resellers and businesses with flexible quantities and dedicated support.": "สินค้าดิจิทัลขายส่งสำหรับผู้ค้าปลีกและธุรกิจ พร้อมจำนวนที่ยืดหยุ่นและบริการช่วยเหลือเฉพาะ",
  "No active products are available in this collection yet.": "ยังไม่มีสินค้าที่เปิดใช้งานในคอลเลกชันนี้",
  "View all": "ดูทั้งหมด",
  "Shop now": "ซื้อเลย",
  "No products found.": "ไม่พบสินค้า",
  "Accepted payment methods": "วิธีชำระเงินที่รองรับ",
  "Secure payments • Automatic verification": "ชำระเงินปลอดภัย • ยืนยันอัตโนมัติ",
  "InGamePin Support": "ฝ่ายช่วยเหลือ InGamePin",
  "We usually reply shortly": "โดยปกติเราตอบกลับอย่างรวดเร็ว",
  "Start chat": "เริ่มแชต",
  Name: "ชื่อ",
  Email: "อีเมล",
  Message: "ข้อความ",
  Send: "ส่ง",
  "Close chat": "ปิดแชต",
  "Type your message...": "พิมพ์ข้อความ...",
  "Last updated": "อัปเดตล่าสุด",
  "Back to store": "กลับไปที่ร้านค้า",
  "Different products": "สินค้าต่างกัน",
  "Total quantity": "จำนวนรวม",
  "Your product discounts": "ส่วนลดสินค้าของคุณ",
  "USDT network": "เครือข่าย USDT",
  "Top-up pending": "การเติมเงินรอดำเนินการ",
  "Top-up requests": "คำขอเติมเงิน",
  "No wallet top-up requests yet.": "ยังไม่มีคำขอเติมเงินกระเป๋า",
  "Wallet transactions": "ธุรกรรมกระเป๋าเงิน",
  "No wallet transactions yet.": "ยังไม่มีธุรกรรมกระเป๋าเงิน",
  Wallet: "กระเป๋าเงิน",
  Customer: "ลูกค้า",
  Overview: "ภาพรวม",
  "My account": "บัญชีของฉัน",
  "Manage purchases, codes, notifications and wallet balance.": "จัดการการซื้อ โค้ด การแจ้งเตือน และยอดกระเป๋าเงิน",
  "Add money or view transactions →": "เติมเงินหรือดูธุรกรรม →",
  "Total orders": "คำสั่งซื้อทั้งหมด",
  "Available securely below": "พร้อมใช้งานอย่างปลอดภัยด้านล่าง",
  "Newest purchases appear first.": "รายการซื้อล่าสุดจะแสดงก่อน",
  "Track an order": "ติดตามคำสั่งซื้อ",
  "No orders found for this email address.": "ไม่พบคำสั่งซื้อสำหรับอีเมลนี้",
  Products: "สินค้า",
  "My delivered codes": "โค้ดที่จัดส่งแล้วของฉัน",
  "Keep codes private and redeem them only on the official platform.": "เก็บโค้ดเป็นความลับและแลกใช้บนแพลตฟอร์มทางการเท่านั้น",
  Delivered: "จัดส่งแล้ว",
  "No notifications yet.": "ยังไม่มีการแจ้งเตือน",
  "Not added": "ยังไม่ได้เพิ่ม",
  "Email status": "สถานะอีเมล",
  Verified: "ยืนยันแล้ว",
  "Welcome to InGamePin": "ยินดีต้อนรับสู่ InGamePin",
  "Sign in to track orders, access delivered codes and manage your wallet.": "เข้าสู่ระบบเพื่อติดตามคำสั่งซื้อ ดูโค้ดที่จัดส่ง และจัดการกระเป๋าเงิน",
  "Reset password": "รีเซ็ตรหัสผ่าน",
  "We will send a secure reset link to your email.": "เราจะส่งลิงก์รีเซ็ตที่ปลอดภัยไปยังอีเมลของคุณ",
  "Send reset link": "ส่งลิงก์รีเซ็ต",
  "Return to login": "กลับไปเข้าสู่ระบบ",
  "Choose new password": "ตั้งรหัสผ่านใหม่",
  "New password": "รหัสผ่านใหม่",
  "Confirm password": "ยืนยันรหัสผ่าน",
  "Update password": "อัปเดตรหัสผ่าน",
  "Add money to your wallet": "เติมเงินเข้ากระเป๋า",
  "Binance calculates the supported cryptocurrency amount from your USD top-up.": "Binance จะคำนวณจำนวนคริปโทที่รองรับจากยอดเติม USD ของคุณ",
  "Wallet top-up": "เติมเงินกระเป๋า",
  "Cancel and return to wallet": "ยกเลิกและกลับไปกระเป๋าเงิน",
  "Monday - Sunday": "จันทร์ - อาทิตย์",
  "Response Time": "เวลาตอบกลับ",
  "Usually 5–15 mins": "ปกติ 5–15 นาที",
  Language: "ภาษา",
  "English, Hindi, Bengali": "อังกฤษ ฮินดี เบงกาลี",
  "Select state": "เลือกรัฐ/จังหวัด",
  Balance: "ยอดคงเหลือ",
  "Digital Email Delivery": "จัดส่งดิจิทัลทางอีเมล",
  "Delivery instructions will be sent to your email.": "คำแนะนำการจัดส่งจะถูกส่งไปยังอีเมลของคุณ",
  FREE: "ฟรี",
  "Pay securely with Binance": "ชำระอย่างปลอดภัยด้วย Binance",
  "Pay with USDT on TRC20, BEP20, or Solana": "ชำระด้วย USDT ผ่าน TRC20, BEP20 หรือ Solana",
  "Cards and other payment methods": "บัตรและวิธีชำระเงินอื่น",
  "Faster Payments System or USDT": "ระบบชำระเงินด่วนหรือ USDT",
  "Insufficient wallet balance": "ยอดกระเป๋าเงินไม่เพียงพอ",
  "Sign in to use your wallet": "เข้าสู่ระบบเพื่อใช้กระเป๋าเงิน",
  Included: "รวมแล้ว",
  Secure: "ปลอดภัย",
  Genuine: "ของแท้",
  Support: "ช่วยเหลือ",
  "Trending Now": "กำลังเป็นที่นิยม",
  "Find Your Product": "ค้นหาสินค้าของคุณ",
  "Explore Products": "สำรวจสินค้า",
  "Browse all products": "ดูสินค้าทั้งหมด",
  "View product": "ดูสินค้า",
  From: "เริ่มต้น",
  "In stock": "มีสินค้า",
  "Out of stock": "สินค้าหมด",
  "Product Description": "รายละเอียดสินค้า",
  "Game Features": "คุณสมบัติเกม",
  Region: "ภูมิภาค",
  "Digital Product": "สินค้าดิจิทัล",
  "Required customer information": "ข้อมูลลูกค้าที่จำเป็น",
  "Complete the required information for this product.": "กรอกข้อมูลที่จำเป็นสำหรับสินค้านี้",
  "Enter your details": "กรอกข้อมูลของคุณ",
  "Order summary": "สรุปคำสั่งซื้อ",
  "Place Order": "สั่งซื้อ",
  "Processing order...": "กำลังประมวลผลคำสั่งซื้อ...",
  "Creating payment...": "กำลังสร้างการชำระเงิน...",
  "Payment successful": "ชำระเงินสำเร็จ",
  "Your order has been paid successfully.": "ชำระเงินคำสั่งซื้อสำเร็จแล้ว",
  Continue: "ดำเนินการต่อ",
  Back: "ย้อนกลับ",
  "Loading...": "กำลังโหลด...",
  "Please wait...": "โปรดรอ...",
  "Try again": "ลองอีกครั้ง",
  "Something went wrong.": "เกิดข้อผิดพลาด",
  "Payment failed": "ชำระเงินไม่สำเร็จ",
  "The payment was cancelled or could not be completed.": "การชำระเงินถูกยกเลิกหรือไม่สามารถดำเนินการได้",
  "Return to cart": "กลับไปตะกร้า",
  "Order completed": "คำสั่งซื้อเสร็จสมบูรณ์",
  "Thank you for your order.": "ขอบคุณสำหรับคำสั่งซื้อ",
  "Search products": "ค้นหาสินค้า",
  Preorder: "สั่งจองล่วงหน้า",
  "Preorder Now": "สั่งจองตอนนี้",
  "Preorder price": "ราคาสั่งจอง",
  "Launches In": "เปิดตัวใน",
  Days: "วัน",
  Hours: "ชั่วโมง",
  Min: "นาที",
  Sec: "วินาที",
  "Maybe Later": "ไว้ภายหลัง",
  "Customer information": "ข้อมูลลูกค้า",
  "Submit preorder": "ส่งคำสั่งจอง",
  "Secure your preorder": "ยืนยันคำสั่งจองของคุณ",
  "Direct USDT": "USDT โดยตรง",
  PayPalych: "PayPalych",
  FreeKassa: "FreeKassa",
  "Binance Pay": "Binance Pay",
  "My Orders": "คำสั่งซื้อของฉัน",
  "My Codes": "โค้ดของฉัน",
  Affiliate: "พันธมิตร",
  "View and track every purchase.": "ดูและติดตามทุกการซื้อ",
  "Order, payment, and account updates.": "อัปเดตคำสั่งซื้อ การชำระเงิน และบัญชี",
  "Delivered content": "เนื้อหาที่จัดส่ง",
  "Customer details": "ข้อมูลลูกค้า",
  "Payment details": "ข้อมูลการชำระเงิน",
  "Keep these codes private. Each code can normally be redeemed only once.": "เก็บโค้ดเหล่านี้เป็นความลับ โดยปกติแต่ละโค้ดใช้ได้ครั้งเดียว",
  "Verified purchase": "การซื้อที่ยืนยันแล้ว",
  "How was your purchase?": "ประสบการณ์การซื้อเป็นอย่างไร?",
  Positive: "เชิงบวก",
  Negative: "เชิงลบ",
  "Optional comment about your purchase": "ความคิดเห็นเพิ่มเติมเกี่ยวกับการซื้อ (ไม่บังคับ)",
  "Submitting...": "กำลังส่ง...",
  "Submit review": "ส่งรีวิว",
  "Verified reviews": "รีวิวที่ยืนยันแล้ว",
  "Positive / Negative": "เชิงบวก / เชิงลบ",
  "No verified reviews yet": "ยังไม่มีรีวิวที่ยืนยันแล้ว",
  "Customers can review this product after a completed delivery.": "ลูกค้าสามารถรีวิวสินค้านี้หลังการจัดส่งเสร็จสมบูรณ์",
  Description: "รายละเอียด",
  Reviews: "รีวิว",
  "Delivery instructions": "คำแนะนำการจัดส่ง",
  "Generate invoice": "สร้างใบแจ้งหนี้",
  Invoice: "ใบแจ้งหนี้",
  "Invoice ready": "ใบแจ้งหนี้พร้อมแล้ว",
  "Full legal name": "ชื่อ-นามสกุลตามกฎหมาย",
  Country: "ประเทศ",
  "Complete billing address": "ที่อยู่เรียกเก็บเงินแบบเต็ม",
  "House/building, street, city, state, postal code": "บ้าน/อาคาร ถนน เมือง จังหวัด รหัสไปรษณีย์",
  "Tax ID / TIN": "เลขประจำตัวผู้เสียภาษี / TIN",
  "Product / denomination": "สินค้า / มูลค่า",
  Qty: "จำนวน",
  Rate: "ราคา",
  Total: "รวม",
  "This is a computer-generated invoice.": "นี่คือใบแจ้งหนี้ที่สร้างโดยระบบคอมพิวเตอร์",
  "Protect your account with a Passkey": "ปกป้องบัญชีด้วย Passkey",
  "Sign in securely using your phone, fingerprint, face or device PIN.": "เข้าสู่ระบบอย่างปลอดภัยด้วยโทรศัพท์ ลายนิ้วมือ ใบหน้า หรือ PIN อุปกรณ์",
  "Account protection": "การปกป้องบัญชี",
  Security: "ความปลอดภัย",
  "Use a Passkey to sign in without Google Authenticator codes.": "ใช้ Passkey เพื่อเข้าสู่ระบบโดยไม่ต้องใช้รหัส Google Authenticator",
  Passkeys: "Passkey",
  "Loading passkeys...": "กำลังโหลด Passkey...",
  "No passkey is connected yet.": "ยังไม่ได้เชื่อมต่อ Passkey",
  "Enable Passkey": "เปิดใช้ Passkey",
  "Add Passkey": "เพิ่ม Passkey",
  "Sign in with Passkey": "เข้าสู่ระบบด้วย Passkey",
  "Checking passkey...": "กำลังตรวจสอบ Passkey...",
  "Customer App Installed": "ติดตั้งแอปลูกค้าแล้ว",
  "Install Customer App": "ติดตั้งแอปลูกค้า",
  "InGamePin Marketing Partners": "พันธมิตรการตลาด InGamePin",
  "Promote digital products. Earn commission in USDT.": "โปรโมตสินค้าดิจิทัลและรับค่าคอมมิชชันเป็น USDT",
  "Join Affiliate Program": "เข้าร่วมโปรแกรมพันธมิตร",
  "Learn & Join": "เรียนรู้และเข้าร่วม",
  "Ready to become a partner?": "พร้อมเป็นพันธมิตรแล้วหรือยัง?",
  Apply: "สมัคร",
  "Create links": "สร้างลิงก์",
  Promote: "โปรโมต",
  "Earn USDT": "รับ USDT",
  "Affiliate code": "รหัสพันธมิตร",
  "Promotion channel": "ช่องทางโปรโมต",
  Commission: "ค่าคอมมิชชัน",
  "Affiliate application": "ใบสมัครพันธมิตร",
  "Update application": "อัปเดตใบสมัคร",
  "Affiliate applications are currently closed.": "ขณะนี้ปิดรับสมัครพันธมิตร",
  "Your application is waiting for administrator review.": "ใบสมัครของคุณกำลังรอผู้ดูแลตรวจสอบ",
  "Fast Delivery": "จัดส่งรวดเร็ว",
  "Secure Checkout": "ชำระเงินปลอดภัย",
  "Enter other amount": "กรอกจำนวนอื่น",
  "Enter recipient email address": "กรอกอีเมลผู้รับ",
  "Decrease quantity": "ลดจำนวน",
  "Increase quantity": "เพิ่มจำนวน",
  "House number, building and street": "เลขที่บ้าน อาคาร และถนน",
  "Area, colony or locality": "พื้นที่ เขต หรือท้องถิ่น",
  "Nearby landmark": "จุดสังเกตใกล้เคียง",
  "Enter city": "กรอกเมือง",
  "Close live chat": "ปิดแชตสด",
  "Your name": "ชื่อของคุณ",
  "Your email": "อีเมลของคุณ",
  "Main navigation": "เมนูหลัก",
  "Mobile navigation": "เมนูมือถือ",
  Currency: "สกุลเงิน",
};

const russianPatterns: Array<[RegExp, (...matches: string[]) => string]> = [
  [/^Last updated:\s*(.+)$/, (date) => `Последнее обновление: ${date}`],
  [/^(\d+) days$/, (days) => `${days} дней`],
  [/^Commission is tracked only when a customer uses your valid affiliate link and completes an eligible order within the current (\d+)-day tracking period\. Browser settings, deleted cookies, another referral link or technical restrictions may affect attribution\. InGamePin records are final for referral and commission calculations\.$/, (days) => `Комиссия отслеживается, только если покупатель использует вашу действующую партнёрскую ссылку и завершает подходящий заказ в течение ${days}-дневного периода отслеживания. Настройки браузера, удалённые cookie, другая реферальная ссылка или технические ограничения могут повлиять на атрибуцию. Данные InGamePin являются окончательными для расчёта рефералов и комиссии.`],
  [/^Valid commission remains pending for (\d+) days after payment so the order can be checked for refunds, disputes and fraud\. Pending commission cannot be withdrawn\. Only commission shown as available may be included in a payout request\.$/, (days) => `Действительная комиссия остаётся в ожидании ${days} дней после оплаты для проверки возвратов, споров и мошенничества. Ожидающую комиссию вывести нельзя. В заявку на выплату можно включить только доступную комиссию.`],
  [/^The minimum payout request is (.+) USDT\. A fixed (.+) USDT processing fee is deducted from each payout\. Payouts are reviewed and sent manually through enabled USDT networks: (.+)\. You are responsible for entering a compatible network and wallet address\. Blockchain transactions are final and cannot be recovered if the information is incorrect\.$/, (minimum, fee, networks) => `Минимальная сумма выплаты — ${minimum} USDT. Из каждой выплаты вычитается фиксированная комиссия ${fee} USDT. Выплаты проверяются и отправляются вручную через доступные сети USDT: ${networks}. Вы отвечаете за указание совместимой сети и адреса кошелька. Блокчейн-транзакции окончательны и не могут быть восстановлены при неверных данных.`],
  [/^Customer information\s+(.+)$/, (number) => `Данные покупателя ${number}`],
  [/^Only\s+(.+)\s+Left$/, (count) => `Осталось только: ${count}`],
  [/^Hello,\s+(.+)$/, (name) => `Здравствуйте, ${name}`],
  [/^Minimum amount:\s*\$(.+)$/, (amount) => `Минимальная сумма: $${amount}`],
  [/^Order\s+(.+)$/, (number) => `Заказ ${number}`],
  [/^(.+)\s+items?$/, (count) => `${count} товар(ов)`],
  [/^Orders using\s+(.+)$/, (email) => `Заказы пользователя ${email}`],
  [/^We sent an?\s+(?:six|eight)-digit verification code to\s+(.+)\.$/, (email) => `Мы отправили код подтверждения на ${email}.`],
  [/^Invoice expires in\s+(.+)$/, (time) => `Счёт истекает через ${time}`],
  [/^(.+)\s+available$/, (count) => `Доступно: ${count}`],
  [/^Allowed quantity:\s*(.+)$/, (quantity) => `Допустимое количество: ${quantity}`],
  [/^Showing\s+(.+)\s+products?$/, (count) => `Показано товаров: ${count}`],
  [/^(.+)\s+products?$/, (count) => `${count} товар(ов)`],
  [/^Show More\s+(.+)$/, (section) => `Показать больше: ${russianText[section] ?? section}`],
  [/^Open slide\s+(\d+)$/, (number) => `Открыть слайд ${number}`],
  [/^(.+) preorder$/, (name) => `${name} — предзаказ`],
  [/^(.+)\s+Sold$/, (count) => `Продано: ${count}`],
];

const thaiPatterns: Array<[RegExp, (...matches: string[]) => string]> = [
  [/^Customer information\s+(.+)$/, (number) => `ข้อมูลลูกค้า ${number}`],
  [/^Only\s+(.+)\s+Left$/, (count) => `เหลือเพียง ${count}`],
  [/^Hello,\s+(.+)$/, (name) => `สวัสดี ${name}`],
  [/^Minimum amount:\s*\$(.+)$/, (amount) => `จำนวนขั้นต่ำ: $${amount}`],
  [/^Order\s+(.+)$/, (number) => `คำสั่งซื้อ ${number}`],
  [/^(.+)\s+items?$/, (count) => `${count} รายการ`],
  [/^Orders using\s+(.+)$/, (email) => `คำสั่งซื้อของ ${email}`],
  [/^We sent an?\s+(?:six|eight)-digit verification code to\s+(.+)\.$/, (email) => `เราได้ส่งรหัสยืนยันไปยัง ${email}`],
  [/^Invoice expires in\s+(.+)$/, (time) => `ใบแจ้งชำระหมดอายุใน ${time}`],
  [/^(.+)\s+available$/, (count) => `พร้อมจำหน่าย ${count}`],
  [/^Allowed quantity:\s*(.+)$/, (quantity) => `จำนวนที่อนุญาต: ${quantity}`],
  [/^Showing\s+(.+)\s+products?$/, (count) => `แสดงสินค้า ${count} รายการ`],
  [/^(.+)\s+Sold$/, (count) => `ขายแล้ว ${count}`],
];

const originalText = new WeakMap<Text, string>();
const originalAttributes = new WeakMap<Element, Map<string, string>>();
const translatedAttributes = ["placeholder", "title", "aria-label"];

function translateValue(value: string, language: StoreLanguage) {
  const trimmed = value.trim();
  if (!trimmed) return value;
  const normalized = trimmed.replace(/\s+/g, " ");

  const textMap = language === "th" ? thaiText : russianText;
  const patterns = language === "th" ? thaiPatterns : russianPatterns;
  let translated = textMap[normalized];
  if (!translated) {
    for (const [pattern, formatter] of patterns) {
      const match = normalized.match(pattern);
      if (match) {
        translated = formatter(...match.slice(1));
        break;
      }
    }
  }

  if (!translated) return value;
  const leadingSpace = value.match(/^\s*/)?.[0] ?? "";
  const trailingSpace = value.match(/\s*$/)?.[0] ?? "";
  return `${leadingSpace}${translated}${trailingSpace}`;
}

function isExcluded(node: Node) {
  const element =
    node.nodeType === Node.ELEMENT_NODE
      ? (node as Element)
      : node.parentElement;

  return Boolean(
    element?.closest(
      "script, style, code, pre, textarea, [data-no-auto-translate], [contenteditable='true']",
    ),
  );
}

function updatePage(root: HTMLElement, language: StoreLanguage) {
  const shouldTranslate = language !== "en";
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let current = walker.nextNode();

  while (current) {
    const textNode = current as Text;
    if (!isExcluded(textNode)) {
      if (shouldTranslate) {
        const source = originalText.get(textNode) ?? textNode.data;
        const translated = translateValue(source, language);
        if (translated !== source) {
          originalText.set(textNode, source);
          if (textNode.data !== translated) textNode.data = translated;
        }
      } else {
        const source = originalText.get(textNode);
        if (source !== undefined && textNode.data !== source) {
          textNode.data = source;
        }
      }
    }
    current = walker.nextNode();
  }

  for (const element of root.querySelectorAll("*")) {
    if (isExcluded(element)) continue;

    for (const attribute of translatedAttributes) {
      if (!element.hasAttribute(attribute)) continue;

      if (shouldTranslate) {
        const saved = originalAttributes.get(element);
        const source = saved?.get(attribute) ?? element.getAttribute(attribute) ?? "";
        const translated = translateValue(source, language);
        if (translated !== source) {
          const values = saved ?? new Map<string, string>();
          values.set(attribute, source);
          originalAttributes.set(element, values);
          if (element.getAttribute(attribute) !== translated) {
            element.setAttribute(attribute, translated);
          }
        }
      } else {
        const source = originalAttributes.get(element)?.get(attribute);
        if (source !== undefined && element.getAttribute(attribute) !== source) {
          element.setAttribute(attribute, source);
        }
      }
    }
  }
}

export default function RussianWebsiteTranslator() {
  const pathname = usePathname();
  const { language } = useStorePreferences();

  useEffect(() => {
    if (pathname.startsWith("/admin")) return;

    const root = document.body;
    const observer = new MutationObserver(() => {
      observer.disconnect();
      updatePage(root, language);
      observer.observe(root, {
        childList: true,
        subtree: true,
        characterData: true,
        attributes: true,
        attributeFilter: translatedAttributes,
      });
    });

    updatePage(root, language);
    observer.observe(root, {
      childList: true,
      subtree: true,
      characterData: true,
      attributes: true,
      attributeFilter: translatedAttributes,
    });

    return () => observer.disconnect();
  }, [language, pathname]);

  return null;
}
