import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import AdminSidebar from "../../../AdminSidebar";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
export default async function OrderReceipt({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/admin/login"); const access = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle(); if (!access.data) redirect("/admin/login?error=Access denied");
  const admin = createAdminClient(); const [orderResult, itemsResult, paymentResult] = await Promise.all([admin.from("orders").select("id, order_number, customer_name, customer_email, customer_phone, currency, subtotal, discount, total, status, customer_note, admin_note, created_at, paid_at, delivered_at").eq("id", id).maybeSingle(), admin.from("order_items").select("id, product_name, option_name, denomination, platform, fulfillment_mode, player_id, quantity, unit_price, total_price").eq("order_id", id).order("created_at"), admin.from("payments").select("method, status, amount, currency, transaction_id, gateway_order_id, gateway_payment_id, submitted_at, verified_at").eq("order_id", id).order("created_at", { ascending: false }).limit(1).maybeSingle()]); if (!orderResult.data) notFound(); const order = orderResult.data; const payment = paymentResult.data; const items = itemsResult.data ?? []; const itemIds = items.map((item) => item.id); const codesResult = itemIds.length ? await admin.from("gift_card_codes").select("id, order_item_id, code, sold_at").in("order_item_id", itemIds).eq("status", "SOLD").order("sold_at") : { data: [] }; const codesByItem = new Map<string, string[]>(); for (const code of codesResult.data ?? []) { if (!code.order_item_id) continue; codesByItem.set(code.order_item_id, [...(codesByItem.get(code.order_item_id) ?? []), code.code]); }
  const detail = (label: string, value: React.ReactNode) => <div className="grid min-w-0 gap-2 border-b border-slate-200 py-3 sm:grid-cols-[170px_minmax(0,1fr)]"><span className="text-sm text-slate-500">{label}</span><span className="min-w-0 break-all text-sm font-medium">{value || "—"}</span></div>;
  return <div className="min-h-screen bg-white text-slate-900"><div className="mx-auto flex min-h-screen max-w-[1500px] flex-col lg:flex-row"><AdminSidebar /><main className="min-w-0 flex-1 p-5 sm:p-8"><header className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Order receipt</p><h1 className="mt-2 text-3xl font-black">{order.order_number}</h1></div><Link href="/admin/orders" className="h-fit rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">← Orders</Link></header><section className="mt-8 rounded-2xl border border-slate-200 p-5 shadow-sm sm:p-6">
    <div className="grid gap-x-8 lg:grid-cols-2"><div><h2 className="text-lg font-black">Customer and order</h2>{detail("Customer name", order.customer_name)}{detail("Email", order.customer_email)}{detail("Phone", order.customer_phone)}{detail("Order status", order.status)}{detail("Order created", new Date(order.created_at).toLocaleString())}{detail("Paid at", order.paid_at ? new Date(order.paid_at).toLocaleString() : null)}{detail("Delivered at", order.delivered_at ? new Date(order.delivered_at).toLocaleString() : null)}</div><div><h2 className="text-lg font-black">Payment</h2>{detail("Payment method", payment?.method)}{detail("Payment status", payment?.status)}{detail("Transaction ID", payment?.transaction_id)}{detail("Gateway order ID", payment?.gateway_order_id)}{detail("Gateway payment ID", payment?.gateway_payment_id)}{detail("Verified at", payment?.verified_at ? new Date(payment.verified_at).toLocaleString() : null)}</div></div>
    <div className="mt-7 overflow-x-auto"><h2 className="mb-3 text-lg font-black">Products</h2><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">Option</th><th className="px-4 py-3">Qty</th><th className="px-4 py-3">Price</th><th className="px-4 py-3">Total</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-t border-slate-200"><td className="px-4 py-3 font-bold">{item.product_name}</td><td className="px-4 py-3">{item.option_name ?? item.denomination ?? "—"}</td><td className="px-4 py-3">{item.quantity}</td><td className="px-4 py-3">{Number(item.unit_price).toFixed(2)}</td><td className="px-4 py-3 font-bold">{Number(item.total_price).toFixed(2)} {order.currency}</td></tr>)}</tbody></table></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_320px]"><div>{items.map((item) => { const codes = codesByItem.get(item.id) ?? []; return codes.length ? <div key={item.id} className="mb-3 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-sm font-bold text-blue-700">{item.product_name} · Delivered codes</p>{codes.map((code) => <p key={code} className="mt-2 font-mono font-black">{code}</p>)}</div> : null; })}</div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4">{detail("Subtotal", `${Number(order.subtotal).toFixed(2)} ${order.currency}`)}{detail("Discount", `${Number(order.discount).toFixed(2)} ${order.currency}`)}{detail("Total", `${Number(order.total).toFixed(2)} ${order.currency}`)}</div></div>
  </section></main></div></div>;
}
