const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function load(file,imports={}) { const mod={exports:{}};new Function('exports','require','module',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.ReactJSX}}).outputText)(mod.exports,n=>n in imports?imports[n]:require(n),mod);return mod.exports; }
const helpers=load('lib/wallet-receipt.ts');
const uid='6830c424-bf30-4334-97ec-1e2c7f10ce47',tid='8faf8342-736f-42fb-a7e1-c44a47ef90c1',rid='e1191f1d-cf7a-4917-a11a-afefb5d76034',hash='0x'+'a'.repeat(64);
function setup(options={}) {
 const queries=[];let adminCreated=0;
 const tx={id:tid,user_id:uid,transaction_type:'CREDIT',amount:1000,balance_before:29.14,balance_after:1029.14,description:'Direct USDT wallet top-up',reference_id:rid,created_at:'2026-09-16T12:42:04Z',...options.transaction};
 const topup={id:rid,user_id:uid,amount:1000,currency:'USD',payment_method:'USDT_DIRECT',status:'APPROVED',gateway_order_id:'invoice',gateway_transaction_id:hash,...options.topup};
 const invoice={invoiceId:'invoice',orderId:rid,network:'BEP20',token:'USDT',address:'0x'+'b'.repeat(40),amount:'1000.00',status:'PAID',paidAt:1789562524,transactionHash:hash,payerAddress:'0x'+'c'.repeat(40),receivedAmount:'1000.00',...options.invoice};
 function from(table){const filters={};const query={select(){return query;},eq(k,v){filters[k]=v;return query;},async maybeSingle(){queries.push({table,filters});let data=table==='wallet_transactions'?(options.missing?null:tx):table==='customer_wallets'?{currency:'USD'}:table==='wallet_topup_requests'?(options.noTopup?null:topup):table==='orders'?options.order:null;if(data&&filters.user_id&&data.user_id&&data.user_id!==filters.user_id)data=null;return {data,error:null};}};return query;}
 const admin={from,auth:{admin:{getUserById:async()=>({data:{user:{id:uid,email:'customer@example.com',user_metadata:{name:'Customer'}}},error:null})}}};
 const session={auth:{getUser:async()=>({data:{user:options.loggedOut?null:{id:'admin'}}})},from:()=>({select(){return this;},eq(){return this;},maybeSingle:async()=>({data:options.denied?null:{user_id:'admin'}})})};
 const page=load('app/admin/customers/[id]/transactions/[transactionId]/page.tsx',{'./Receipt.module.css':{default:{receipt:'wallet-receipt'}},'next/link':{default:({children,prefetch,...props})=>React.createElement('a',props,children)},'next/navigation':{notFound(){throw Error('404');},redirect(url){throw Error('redirect:'+url);}},'@/lib/supabase/admin-session':{createClient:async()=>session},'@/lib/supabase/admin':{createAdminClient:()=>{adminCreated++;return admin;}},'@/lib/payment-method-label':{formatPaymentMethod:m=>m},'@/lib/usdt-gateway':{getUsdtInvoice:async()=>{if(options.offline)throw Error('private gateway detail');return invoice;}},'@/lib/wallet-receipt':helpers,'@/app/admin/invoices/[id]/PrintSavedInvoiceButton':{default:()=>React.createElement('button',null,'Print / Save PDF')}}).default;
 return {queries,adminCreated:()=>adminCreated,render:async(id=uid)=>renderToStaticMarkup(await page({params:Promise.resolve({id,transactionId:tid})}))};
}
test('top-up receipt includes saved credit, hash, addresses and verified explorer link',async()=>{const f=setup();const html=await f.render();assert.match(html,/1,000.00/);assert.match(html,/1,029.14/);assert.ok(html.includes('https://bscscan.com/tx/'+hash));assert.match(html,/IST/);assert.match(html,/Sender address/);assert.ok(f.queries.some(q=>q.table==='wallet_transactions'&&q.filters.id===tid&&q.filters.user_id===uid));});
test('signed-out or non-admin requests cannot create the privileged client',async()=>{for(const opt of [{loggedOut:true},{denied:true}]){const f=setup(opt);await assert.rejects(f.render(),/redirect/);assert.equal(f.adminCreated(),0);}});
test('another customer cannot access the transaction through a swapped route',async()=>{await assert.rejects(setup().render('11111111-1111-4111-8111-111111111111'),/404/);});
test('gateway outage preserves receipt without leaking error text or inventing a network',async()=>{const html=await setup({offline:true}).render();assert.match(html,/gateway is temporarily unavailable/);assert.ok(html.includes(hash));assert.doesNotMatch(html,/private gateway detail|bscscan.com/);});
test('mismatched gateway receipt is not attached to a top-up',async()=>{const html=await setup({invoice:{orderId:'wrong'}}).render();assert.match(html,/could not be matched/);assert.doesNotMatch(html,/bscscan.com|Sender address/);});
test('order debits show line items and full order receipt link',async()=>{const oid='22222222-2222-4222-8222-222222222222';const html=await setup({transaction:{transaction_type:'DEBIT',amount:128.29,balance_before:1029.14,balance_after:900.85,order_id:oid,reference_id:'IGP-TEST'},order:{id:oid,customer_id:uid,order_number:'IGP-TEST',status:'DELIVERED',total:128.29,currency:'USD',created_at:'2026-09-16T12:44:00Z',order_items:[{id:'item',product_name:'Gift card',option_name:'2000 INR',quantity:2,unit_price:64.145,total_price:128.29}]}}).render();assert.match(html,/Gift card/);assert.match(html,/View full order receipt/);assert.match(html,/900.85/);});
test('manual credit without gateway and unlinked entry still have receipts',async()=>{assert.doesNotMatch(await setup({topup:{payment_method:'UPI',gateway_order_id:null}}).render(),/Blockchain payment receipt/);assert.match(await setup({noTopup:true}).render(),/no linked top-up or order record/);});
test('explorer links validate hashes and never guess a network',()=>{assert.equal(helpers.receiptExplorerUrl('UNKNOWN',hash),null);assert.equal(helpers.receiptExplorerUrl('BEP20','javascript:bad'),null);assert.equal(helpers.receiptExplorerUrl('TRC20','a'.repeat(64)),'https://tronscan.org/#/transaction/'+'a'.repeat(64));assert.equal(helpers.receiptExplorerUrl('SOLANA','2'.repeat(88)),'https://solscan.io/tx/'+'2'.repeat(88));});
