import type { Metadata } from "next";
import PolicyPage from "../../components/PolicyPage";

export const metadata: Metadata = { title: "Terms & Conditions" };

const EFFECTIVE_DATE = "13 August 2026";

export default function TermsPage() {
  return (
    <PolicyPage
      eyebrow="Legal"
      title="Terms & Conditions"
      summary="These terms govern access to InGamePin and purchases of gaming top-ups, gift cards, subscriptions and game keys. InGamePin is operated by AMAN G."
      sections={[
        { title: "Effective date and acceptance", content: <><p><strong>Effective date:</strong> {EFFECTIVE_DATE}</p><p>By accessing InGamePin, creating an account or placing an order, you agree to these Terms & Conditions and the policies linked on this website. If you do not agree, do not use the service.</p></> },
        { title: "Business identity", content: <><p><strong>Operator and trade name:</strong> AMAN G<br /><strong>GSTIN:</strong> 19CMAPG4174K1ZV<br /><strong>Registered address:</strong> Chandpur Leningarh, near Jagorani Sangha Club, South Jogendra Nagar, Kolkata, West Bengal 700110, India<br /><strong>Email:</strong> <a href="mailto:support@ingamepin.com">support@ingamepin.com</a><br /><strong>WhatsApp:</strong> <a href="https://wa.me/919073045011">+91 90730 45011</a><br /><strong>Telegram:</strong> <a href="https://t.me/ingamepinsupport">@ingamepinsupport</a></p><p>References to “InGamePin”, “we”, “us” and “our” mean the InGamePin business operated by AMAN G.</p></> },
        { title: "Eligibility and account responsibility", content: <><p>You must be legally capable of entering a contract under applicable law. If you are a minor, a parent or legal guardian must make or authorize the purchase.</p><p>You are responsible for providing accurate order information, safeguarding login credentials and activity performed through your account. Notify us promptly if you suspect unauthorized access.</p></> },
        { title: "Products and regional restrictions", content: <><p>We sell digital products, including Gaming Top-Ups, Gift Cards, Subscriptions and Game Keys. Product availability, pricing, stock and delivery estimates may change before an order is accepted.</p><p>Products may be restricted by country, region, currency, platform, account type, device, publisher rules or activation period. You must review the product description and confirm compatibility before ordering.</p></> },
        { title: "Orders and customer information", content: <><p>An order is an offer to purchase. We may accept, reject, hold or cancel it for stock issues, pricing or description errors, suspected fraud, sanctions or legal compliance, payment failure, or inability to verify necessary details.</p><p>For player-ID top-ups, you must provide the correct player ID, server, zone and other requested identifiers. A successfully credited top-up cannot normally be reversed or transferred.</p></> },
        { title: "Prices, taxes and payment", content: <><p>The checkout page shows the product price, applicable payment-gateway fee and final order total in the selected display currency. Settlement may be processed in another supported currency or digital asset by the selected provider.</p><p>Available methods may include InGamePin Wallet, Binance Pay, FreeKassa, Pally, direct USDT networks and other methods displayed at checkout. Provider, network and currency-conversion charges outside the displayed order total are the customer’s responsibility unless stated otherwise.</p><p>An order is paid only after payment is confirmed through our records or the provider’s authenticated notification. Taxes are handled according to the transaction and applicable law.</p></> },
        { title: "Delivery", content: <><p>Products may be delivered instantly from available inventory or fulfilled manually after successful payment verification and applicable risk checks. The product page identifies the relevant delivery method and estimate.</p><p>Delivery may occur on-screen, by email, through the customer account, as a downloadable file, or by direct credit to the submitted player account. Delivery estimates are not guarantees where supplier availability, publisher systems, maintenance, incorrect information or security review causes delay.</p></> },
        { title: "Digital codes and licenses", content: <><p>Gift cards, subscription codes and game keys are licensed digital entitlements subject to the issuer’s terms. Associated games, services, brands and intellectual property remain with their respective owners.</p><p>A code is treated as delivered when made available through the stated delivery channel. Keep codes confidential. We may request redemption-error evidence and issuer or platform details when investigating a claim.</p></> },
        { title: "Cancellations, returns and refunds", content: <><p>Digital orders may be processed immediately. Cancellation is not guaranteed after processing, code disclosure or successful top-up. Eligibility and the claim process are described in our <a href="/refund-policy">Return & Refund Policy</a>, which forms part of these terms.</p></> },
        { title: "Acceptable use", content: <><p>You must not use InGamePin for fraud, money laundering, unauthorized payments, unlawful resale, service disruption, scraping, malicious code, impersonation, or attempts to bypass security, purchase limits or regional restrictions.</p><p>We may hold orders, restrict access or close accounts where reasonably necessary to protect customers, InGamePin or service providers and to comply with applicable law.</p></> },
        { title: "Disclaimers and liability", content: <><p>Third-party publisher, platform, payment and network services are outside our control. To the extent permitted by law, InGamePin is not liable for indirect or consequential loss or loss caused by customer-supplied errors, incompatibility or misuse.</p><p>Nothing in these terms excludes liability that cannot legally be excluded or limits a non-waivable statutory consumer right.</p></> },
        { title: "Governing law and disputes", content: <><p>These terms are governed by the laws of India. Courts having jurisdiction under applicable Indian law may hear disputes. International customers may also retain mandatory consumer rights that apply in their place of residence.</p><p>Please contact us before formal proceedings so we can attempt to resolve the matter.</p></> },
        { title: "Grievance officer and contact", content: <><p><strong>Grievance Officer:</strong> AMAN G<br /><strong>Email:</strong> <a href="mailto:support@ingamepin.com">support@ingamepin.com</a><br /><strong>WhatsApp:</strong> <a href="https://wa.me/919073045011">+91 90730 45011</a><br /><strong>Telegram:</strong> <a href="https://t.me/ingamepinsupport">@ingamepinsupport</a></p><p>Please include your order number and account email when contacting us about a purchase.</p></> },
      ]}
    />
  );
}
