import type { Metadata } from "next";
import PolicyPage from "../../components/PolicyPage";

export const metadata: Metadata = { title: "Terms & Conditions" };

export default function TermsPage() {
  return (
    <PolicyPage
      eyebrow="Legal"
      title="Terms & Conditions"
      summary="These terms govern your access to InGamePin and purchases of gaming top-ups, gift cards, subscriptions and game keys. InGamePin is operated by AMAN G."
      sections={[
        { title: "Acceptance and operator", content: <><p>By accessing InGamePin, creating an account or placing an order, you agree to these Terms & Conditions and the policies linked on this website. If you do not agree, do not use the service.</p><p>InGamePin is operated by AMAN G. References to “InGamePin”, “we”, “us” and “our” mean the InGamePin business operated by AMAN G.</p></> },
        { title: "Eligibility and account responsibility", content: <><p>You must be legally capable of entering a contract under applicable law. If you are a minor, a parent or legal guardian must make or authorize the purchase.</p><p>You are responsible for accurate account and order information, safeguarding login credentials, and activity performed through your account. Tell us promptly if you suspect unauthorized access.</p></> },
        { title: "Products and restrictions", content: <><p>We sell digital products, including Gaming Top-Ups, Gift Cards, Subscriptions and Game Keys. Product availability, pricing and delivery estimates may change before an order is accepted.</p><p>Products may be restricted by country or region, currency, gaming platform, account type, device, publisher rules or activation period. You must review the product description and confirm compatibility before ordering. We are not responsible when a correctly supplied product cannot be used because the customer selected the wrong region, platform or account.</p></> },
        { title: "Orders and customer information", content: <><p>An order is an offer to purchase. We may accept, reject, hold or cancel it for stock issues, pricing or description errors, suspected fraud, sanctions or legal compliance, payment failure, or inability to verify necessary details.</p><p>For player-ID top-ups, you must provide the correct player ID, server, zone and other requested identifiers. Once a top-up is successfully credited to the submitted account, it cannot normally be reversed or transferred.</p></> },
        { title: "Prices and payment", content: <><p>The checkout page shows the payable price and available method. Supported methods may include UPI, Binance Pay and the InGamePin Wallet. Bank, network, currency-conversion or blockchain-related charges imposed by third parties are your responsibility unless stated otherwise.</p><p>Payments may require automatic or manual verification. For manual verification, we may request a valid transaction reference or proof of payment. A payment screenshot alone does not establish receipt. An order is paid only after funds are confirmed through our payment records or provider.</p><p>InGamePin Wallet balances are store value for eligible InGamePin purchases, are not a bank account, do not earn interest, and are not transferable or redeemable for cash except where required by law or expressly stated.</p></> },
        { title: "Delivery", content: <><p>Orders are fulfilled manually after successful payment verification and applicable risk checks. Delivery may occur on-screen, by email, through the customer account, or by direct credit to the submitted player account.</p><p>Delivery times are estimates, not guarantees. Verification, supplier availability, publisher systems, maintenance, incorrect information or security review may cause delay. Keep order details and delivered codes confidential.</p></> },
        { title: "Digital codes and licenses", content: <><p>Gift cards, subscription codes and game keys are licensed digital entitlements subject to the issuer’s terms. Ownership of associated games, services, brands and intellectual property remains with their respective owners.</p><p>A code is treated as delivered when made available through the stated delivery channel. Do not disclose it. We may ask for activation-error evidence and issuer/platform details when investigating an invalid-code claim.</p></> },
        { title: "Cancellations, returns and refunds", content: <><p>Digital orders are often processed immediately. Cancellation is not guaranteed after processing, code disclosure or successful top-up. Refund eligibility and the claim process are described in our <a href="/refund-policy">Return & Refund Policy</a>, which forms part of these terms.</p></> },
        { title: "Acceptable use", content: <><p>You must not use InGamePin for fraud, money laundering, unauthorized payments, resale that violates issuer rules, service disruption, scraping, malicious code, impersonation, unlawful activity, or attempts to bypass security, purchase limits or regional restrictions.</p><p>We may restrict access, hold orders or close accounts where reasonably necessary to protect customers, InGamePin or service providers, while respecting applicable law.</p></> },
        { title: "Disclaimers and liability", content: <><p>We aim to provide accurate, secure and available services, but third-party publisher, platform, payment and network services are outside our control. To the extent permitted by law, InGamePin is not liable for indirect, incidental, special or consequential loss, or loss caused by customer-supplied errors or misuse.</p><p>Nothing in these terms excludes liability that cannot legally be excluded or limits any non-waivable statutory consumer right.</p></> },
        { title: "Changes, law and disputes", content: <><p>We may update these terms prospectively by posting a revised version and date. The terms in force when your order is placed normally govern that purchase.</p><p>These terms are governed by the laws of India. Courts with jurisdiction under applicable Indian law may hear disputes. Before formal proceedings, please contact us so we can try to resolve the matter.</p></> },
        { title: "Contact and grievance officer", content: <><p>For support, complaints or legal notices, email <a href="mailto:support@ingamepin.com">support@ingamepin.com</a>.</p><p><strong>Grievance Officer:</strong> AMAN G<br /><strong>Email:</strong> <a href="mailto:support@ingamepin.com">support@ingamepin.com</a></p></> },
      ]}
    />
  );
}
