import type { Metadata } from "next";
import PolicyPage from "../../components/PolicyPage";

export const metadata: Metadata = { title: "Return & Refund Policy" };

export default function RefundPolicyPage() {
  return <PolicyPage eyebrow="Customer Policy" title="Return & Refund Policy" summary="This policy explains cancellations, replacements and refunds for digital products purchased from InGamePin, operated by AMAN G." sections={[
    { title: "Digital-product policy", content: <><p>Gaming Top-Ups, Gift Cards, Subscriptions and Game Keys are digital products that may be fulfilled immediately and cannot be physically returned. Once a valid code is revealed or a top-up or subscription is successfully applied, the order is normally final.</p><p>This does not affect any refund, replacement or other remedy required by applicable consumer law.</p></> },
    { title: "When a remedy may be available", content: <><p>Contact us if a paid product was not delivered within the stated or a reasonable delivery time, a delivered code was already redeemed before delivery or is confirmed invalid, the wrong product was delivered due to our error, a top-up failed and was not credited, or you were charged more than once for the same order.</p><p>After verification, the remedy may be re-delivery, replacement, InGamePin Wallet credit, or refund to the original payment method, as appropriate and subject to law.</p></> },
    { title: "Generally non-refundable cases", content: <><ul><li>A valid code has been viewed, copied, shared, redeemed or resold.</li><li>A top-up was successfully credited to the player ID, server or zone supplied by the customer.</li><li>The customer chose an incompatible region, platform, currency, edition or account.</li><li>The product is unwanted after correct delivery, or the customer’s account is restricted by a publisher or platform.</li><li>Payment cannot be verified as received by InGamePin.</li></ul><p>We will still provide a remedy where applicable law requires one.</p></> },
    { title: "Cancellation", content: <><p>Request cancellation immediately. We may cancel and refund an order only while it remains unprocessed and no code, entitlement or top-up has been supplied. Payment verification or manual preparation may begin promptly, so a cancellation request does not guarantee cancellation.</p></> },
    { title: "How to make a claim", content: <><p>Email <a href="mailto:support@ingamepin.com">support@ingamepin.com</a> promptly with your order number, account email, product, issue description, and relevant screenshots or error messages. Never send passwords, OTPs, full payment credentials or private wallet keys.</p><p>For code issues, retain the code confidentially and provide the platform’s redemption error and, if requested, evidence from the issuer showing activation or redemption status. For player-ID top-ups, provide the submitted ID/server and a relevant account transaction screenshot.</p></> },
    { title: "Investigation and processing", content: <><p>We may verify payment, delivery logs, code status, player-account credit and supplier or publisher records. We may ask for additional information reasonably needed to prevent fraud and decide the claim.</p><p>Approved refunds are initiated to the original payment method where practical. Binance Pay timing depends on the relevant provider or network. InGamePin Wallet refunds are credited to the customer wallet. Any displayed processing time is an estimate; financial providers may take additional time.</p></> },
    { title: "Payment failures and chargebacks", content: <><p>If funds were debited but InGamePin did not receive them, first allow the payment provider’s reversal period and contact us with the transaction reference. Do not make duplicate payments unless instructed.</p><p>Please contact us before raising a payment dispute so we can investigate. Fraudulent chargebacks or false claims may lead to account restriction and lawful recovery action.</p></> },
    { title: "Contact and grievance officer", content: <><p>InGamePin is operated by AMAN G. Refund requests and complaints may be sent to <a href="mailto:support@ingamepin.com">support@ingamepin.com</a>.</p><p><strong>Grievance Officer:</strong> AMAN G<br /><strong>Email:</strong> <a href="mailto:support@ingamepin.com">support@ingamepin.com</a></p></> },
  ]} />;
}
