import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import AdminSidebar from "../../../../AdminSidebar";
import ProductCustomerFieldsEditor from "@/components/ProductCustomerFieldsEditor";
import ProductEditPageTabs from "@/components/ProductEditPageTabs";
import { createClient } from "@/lib/supabase/server";
import { saveCustomerInformation } from "./actions";
export const dynamic = "force-dynamic";
export default async function CustomerInformationPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { id } = await params; const { success, error } = await searchParams; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/admin/login"); const access = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle(); if (!access.data) redirect("/admin/login?error=Access denied"); const [productResult, fieldsResult] = await Promise.all([supabase.from("products").select("id, name, slug").eq("id", id).maybeSingle(), supabase.from("product_customer_fields").select("id, label, placeholder, field_type, is_required").eq("product_id", id).order("sort_order")]); if (!productResult.data) notFound(); const product = productResult.data;
  return <div className="min-h-screen bg-white text-slate-900"><div className="mx-auto flex min-h-screen max-w-[1500px] flex-col lg:flex-row"><AdminSidebar /><main className="min-w-0 flex-1 p-5 sm:p-8"><header className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Product settings</p><h1 className="mt-2 text-3xl font-black">{product.name}</h1><p className="mt-1 text-sm text-slate-500">{product.slug}</p></div><Link href="/admin/products" className="h-fit rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">← Product list</Link></header>{success && <div className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-700">{success}</div>}{error && <div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}<div className="mt-8"><ProductEditPageTabs productId={id} current="customer-information" /></div><form action={saveCustomerInformation} className="mt-6 grid gap-6"><input type="hidden" name="id" value={id} /><ProductCustomerFieldsEditor initialFields={(fieldsResult.data ?? []).map((field) => ({ id: field.id, label: field.label, placeholder: field.placeholder ?? "", fieldType: field.field_type as "TEXT" | "EMAIL" | "NUMBER" | "TEXTAREA", isRequired: field.is_required }))} /><div className="flex justify-end"><button className="rounded-xl bg-slate-900 px-7 py-3 font-black text-white">Save Customer Information</button></div></form></main></div></div>;
}
