import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import AdminSidebar from "../../../../AdminSidebar";
import ProductEditPageTabs from "@/components/ProductEditPageTabs";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import SoldProductsTable from "./SoldProductsTable";
export const dynamic = "force-dynamic";
export default async function SoldProductsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/admin/login"); const access = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle(); if (!access.data) redirect("/admin/login?error=Access denied");
  const admin = createAdminClient(); const [productResult, itemsResult] = await Promise.all([admin.from("products").select("id, name, slug").eq("id", id).maybeSingle(), admin.from("order_items").select("id, order_id, option_name, denomination, total_price, created_at").eq("product_id", id).order("created_at", { ascending: false }).limit(500)]); if (!productResult.data) notFound(); const product = productResult.data; const items = itemsResult.data ?? []; const orderIds = [...new Set(items.map((item) => item.order_id))];
  const ordersResult = orderIds.length ? await admin.from("orders").select("id, order_number, customer_email, currency, status, paid_at, delivered_at").in("id", orderIds).in("status", ["PAID", "PROCESSING", "DELIVERED", "REFUNDED"]) : { data: [] }; const orders = new Map((ordersResult.data ?? []).map((order) => [order.id, order]));
  const rows = items.flatMap((item) => { const order = orders.get(item.order_id); return order ? [{ saleId: item.id, orderId: item.order_id, orderNumber: order.order_number, soldAt: order.delivered_at ?? order.paid_at ?? item.created_at, optionName: item.option_name ?? `${item.denomination ?? ""} denomination`, customerEmail: order.customer_email, paid: `${Number(item.total_price).toFixed(2)} ${order.currency}` }] : []; });
  return <div className="min-h-screen bg-white text-slate-900"><div className="mx-auto flex min-h-screen max-w-[1500px] flex-col lg:flex-row"><AdminSidebar /><main className="min-w-0 flex-1 p-5 sm:p-8"><header className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Product settings</p><h1 className="mt-2 text-3xl font-black">{product.name}</h1><p className="mt-1 text-sm text-slate-500">{product.slug}</p></div><Link href="/admin/products" className="h-fit rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">← Product list</Link></header><div className="mt-8"><ProductEditPageTabs productId={id} current="sold-products" /></div><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Sold products</h2><p className="mt-1 text-sm text-slate-500">Order ID opens order receipt. Product opens delivery receipt.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">{rows.length} sold</span></div><SoldProductsTable productId={id} rows={rows} /></section></main></div></div>;
}
