import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import AdminSidebar from "../../../../../AdminSidebar";
import { completeManualOrder } from "@/app/admin/orders/actions";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";
export default async function ProductReceipt({ params }: { params: Promise<{ id: string; saleId: string }> }) {
  const { id, saleId } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/admin/login"); const access = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle(); if (!access.data) redirect("/admin/login?error=Access denied");
  const admin = createAdminClient(); const itemResult = await admin.from("order_items").select("id, order_id, product_name, option_name, denomination, quantity, total_price, fulfillment_mode, products!inner(delivery_type)").eq("id", saleId).eq("product_id", id).maybeSingle(); if (!itemResult.data) notFound(); const item = itemResult.data; const relation = Array.isArray(item.products) ? item.products[0] : item.products; const isManual = relation?.delivery_type === "MANUAL";
  const [orderResult, paymentResult, codesResult] = await Promise.all([admin.from("orders").select("id, order_number, customer_email, currency, status, created_at, paid_at, delivered_at").eq("id", item.order_id).maybeSingle(), admin.from("payments").select("method, status, transaction_id").eq("order_id", item.order_id).order("created_at", { ascending: false }).limit(1).maybeSingle(), admin.from("gift_card_codes").select("id, code, sold_at").eq("order_item_id", item.id).eq("status", "SOLD").order("sold_at")]); if (!orderResult.data) notFound(); const order = orderResult.data; const payment = paymentResult.data; const codes = codesResult.data ?? [];
  const row = (label: string, value: React.ReactNode) => <div className="grid gap-2 border-b border-slate-200 py-3 sm:grid-cols-[180px_1fr]"><span className="text-sm text-slate-500">{label}</span><span className="text-sm font-medium">{value || "—"}</span></div>;
  return <div className="min-h-screen bg-white text-slate-900"><div className="mx-auto flex min-h-screen max-w-[1500px] flex-col lg:flex-row"><AdminSidebar /><main className="min-w-0 flex-1 p-5 sm:p-8"><header className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Sold product</p><h1 className="mt-2 text-3xl font-black">Product receipt</h1><p className="mt-1 text-sm text-slate-500">{order.order_number}</p></div><Link href={`/admin/products/${id}/edit/sold-products`} className="h-fit rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">← Sold products</Link></header><section className="mt-8 rounded-2xl border border-slate-200 p-5 shadow-sm sm:p-6"><div className="grid gap-x-8 lg:grid-cols-2"><div>{row("Order ID", order.order_number)}{row("Order created", new Date(order.created_at).toLocaleString())}{row("Buyer", order.customer_email)}{row("Payment", `${payment?.method ?? "—"} · ${payment?.status ?? "—"}`)}</div><div>{row("Product", item.product_name)}{row("Denomination", item.option_name ?? item.denomination)}{row("Quantity", item.quantity)}{row("Paid", `${Number(item.total_price).toFixed(2)} ${order.currency}`)}{row("Delivery type", isManual ? "Manual" : "Instant")}</div></div>
  {codes.length > 0 && <div className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="text-sm font-bold text-blue-700">Delivered voucher codes</p>{codes.map((code) => <p key={code.id} className="mt-2 font-mono text-lg font-black tracking-wider">{code.code}</p>)}</div>}
  {isManual && order.status === "PROCESSING" && <form action={completeManualOrder} className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5"><input type="hidden" name="order_id" value={order.id} /><h2 className="text-lg font-black">Manual delivery</h2>{item.fulfillment_mode === "PLAYER_ID_TOPUP" ? <label className="mt-4 flex items-center gap-3"><input type="checkbox" name={`completed_${item.id}`} required /><span className="font-bold">Mark player top-up completed</span></label> : <label className="mt-4 block"><span className="text-sm font-bold">Codes delivered to customer</span><textarea name={`codes_${item.id}`} required rows={5} className="mt-2 w-full rounded-xl border border-amber-200 bg-white px-4 py-3 font-mono" /></label>}<button className="mt-4 rounded-xl bg-slate-900 px-6 py-3 font-black text-white">Complete manual delivery</button></form>}
  </section></main></div></div>;
}
